### ISSUE TITLE
Elusive Stretching Bug

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#1]
Sometimes appears on editor-play mode, possibly fixed

**Comment by grady404** [comment]
Attached is the glitched temp level for your reference. For whatever dumb reason it made me change the extension to txt, just change it back.

[GLITCH-1.txt](https://github.com/cooper-anderson/Blockade/files/460760/GLITCH-1.txt)

**Comment by cooperuser** [comment]
Looked into this one, couldn't find what was causing this duplication bug. Will definitely be fixed on the redo though.

**Comment by grady404** [comment]
Oh ok, didn't see your comment there.

**Comment by grady404** [comment]
Haven't seen this bug in a while. I wonder if it's gone. Did you change anything about the level editing/saving code before the overhaul?

**Comment by cooperuser** [comment]
No, Kinda strange...

**Comment by cooperuser** [comment]
Wait... Maybe

**Comment by grady404** [comment]
What did you change?

**Comment by cooperuser** [comment]
I forget... But I could check the commits. Ill do that now

**Comment by grady404** [comment]
See if you can figure out _why_ it was causing the bug, then we will know for sure that it is gone and can mark this closed. (This is issue #1, it's been around the longest of all the issues, haha)

**Comment by cooperuser** [comment]
Yeah, haha

**Comment by cooperuser** [comment]
The longest by like, 4 seconds, then you put up an issue.

**Comment by grady404** [comment]
Oh true, I forgot about that

**Comment by grady404** [comment]
Check #9 btw

**Comment by grady404** [comment]
Did you find out what was causing this issue? I'd like to mark it as closed.

**Comment by grady404** [comment]
Out of curiosity, what was causing this issue?
