### ISSUE TITLE
Automatically show move buttons on first level

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#21]
On the first level, automatically show the buttons that move the box until the player clicks one of them (not one of the disabled ones, obviously). Once the player moves the box, these buttons should only display when hovering over the box for the rest of the level. Do this every time the player plays the first level, not just the first time, so that if a friend is using their computer to play the game (or other similar scenario), it works the same way.

This is kind of a weird specific, but if the first level happens to have more than one box for some reason, show the buttons on all of the boxes until one of them is moved. That way if someone tries to "mod" their game by changing out all the levels this still works correctly.

**See my comments below.**

**Comment by grady404** [comment]
Small technicality, keep the buttons there until the player _clicks_ one of them, not hovers over it. Or else a player might accidentally pass their mouse over the box and disable the interface, which would confuse them.

**Comment by grady404** [comment]
Know what? I think you should change this feature slightly... have something in the level .json that enables this feature, rather than the fact that it's level 1. (**EDIT:** This would be a `flag`.) That way the level can be moved from the Level 1 spot to a different spot and still work properly, and if someone mods the game with custom levels and they don't want a tutorial for Level 1, they're not forced to have it.

**Comment by grady404** [comment]
And make sure that it's not something that you have to state as "false" in the .jsons of every other level in the entire game.

**Comment by grady404** [comment]
I found another problem with the way this is set up! Since the box is selected when the level begins, the user can press WASD to move it _without hovering over it_. This is bad because then they'll try to move the box with WASD again, and say "wait, why isn't it working?" and be confused. So make sure that when you rewrite this the box is _not_ considered selected when the level begins.

**Comment by cooperuser** [comment]
Duly Noted.
