### ISSUE TITLE
Get rid of TODO everywhere

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#22]
The most important and obvious one is after completing a level. Consider filling this in with a "Congratulations!" and a few statistics about your level completion (move count, etc.)

Consider getting rid of "Help" in the level editor - I think the editor is intuitive enough without that, the only thing that isn't intuitive is how to delete objects (right click), but there might be a way to fix that.

As for the "About" screen we'll work more on that later, for now just write a short little description about the game, say who it's created by and who did what, etc.

There's also the `[temp] Debug` in the bottom left corner when testing levels in the editor.

**Comment by grady404** [comment]
Sample win message that I think you should use:
`Congratulations! It took you 19 moves to complete this level, and you traveled a distance of 78 tiles. Your time was 5:08.`

**Comment by cooperuser** [comment]
I think that the help screen on the editor will make more sense when we get to wiring

**Comment by grady404** [comment]
Well, in that case you'd probably want to do a help page for each individual object (maybe it refers to the documentation)

**Comment by cooperuser** [comment]
maybe if you hover over an item on the select bar for a couple seconds a tooltip pops up?

**Comment by grady404** [comment]
Ah yeah, that's a great idea actually

**Comment by grady404** [comment]
How's the reorganization going btw?

**Comment by cooperuser** [comment]
well right now I am playing a big game of Civ V with a bunch of people from school, so I haven't physically changed anything for about 2 hours, but I've been doing a lot of thinking.

**Comment by grady404** [comment]
Alright. Oh btw what's your steam name?

**Comment by cooperuser** [comment]
`Titanknox`, I use that for pretty much everything besides school stuff

**Comment by grady404** [comment]
Alright I'll add you

**Comment by cooperuser** [comment]
Awesome

**Comment by cooperuser** [comment]
Accepted
