### ISSUE TITLE
Retain bottom toolbar preference (preferences.json)

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#24]
The toolbar at the bottom of the play screen doesn't stay closed between levels. I suggest making a preferences file in which minor things like this can be set, and will persist not only across levels but also across game sessions.

**Comment by cooperuser** [comment]
I had thought of that when I originally added the feature to minimize the bar, but never got around to it

**Comment by grady404** [comment]
Once you reorganize the game's filesystem, you could store `preferences.json` in `/app/save-data/`

**Comment by cooperuser** [comment]
That seems logical, the there could also be a file for custom levels, as you said

**Comment by grady404** [comment]
Yes, `progress`, `custom-levels`, and `progress.json` would all be stored in the same directory

**Comment by grady404** [comment]
I mean `preferences.json`, oops

**Comment by grady404** [comment]
Since the toolbars were removed in version `0.4.1` this issue is no longer relevant.
