### ISSUE TITLE
Click twice on level to enter

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#25]
Allow users to enter a level from the level select screen by clicking on its icon a second time from the level select screen once already selected (not necessarily a double-click, which would imply both clicks must be done consecutively). Currently users must click on the level they wish to enter and then click "Play", however this functionality would allow them to enter levels much more quickly and intuitively.

**Comment by cooperuser** [comment]
thats an easy fix, cause there is a built in `double-click` event

**Comment by grady404** [comment]
Nope, I said NOT double-click, what I meant is once they click one time to select the level, if they click on it a second time (it doesn't matter how long it has been since the first click) they will enter the level

**Comment by cooperuser** [comment]
oh

**Comment by cooperuser** [comment]
thats quite a bit harder

**Comment by grady404** [comment]
No, that seems like it would be very easy. Basically every time someone clicks on a level, check to see if it's the one already selected. If it is, enter that level, if not, change the selected level.

**Comment by cooperuser** [comment]
but we could also have a double click

**Comment by cooperuser** [comment]
yeah i was thinking that

**Comment by grady404** [comment]
Well, a double click would work as intended if you did this, because you're clicking once to select the level, and again to enter it. You don't need to add an explicit double click

**Comment by cooperuser** [comment]
good point....

**Comment by grady404** [comment]
Another note, let's say you click on level 5 to select it, then you click elsewhere on the screen, then you click on the level 5 icon again you should enter it (even though you didn't do both clicks in a row)

**Comment by grady404** [comment]
By elsewhere I don't mean another level, just some random point on the screen

**Comment by cooperuser** [comment]
that would work still

**Comment by cooperuser** [comment]
done

**Comment by grady404** [comment]
Cool

**Comment by cooperuser** [comment]
that was by far easier than I originally thought, cause I at first thought you meant a double click

**Comment by grady404** [comment]
Yeah I figured
