### ISSUE TITLE
Remove the no-symbol cursor when moving boxes

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#27]
Edit: See my comment below.

When you hover over a box to move it, if any of the buttons are disabled they show a "no" symbol cursor when hovering over them. To fix this, you might want to use the CSS property `pointer-events: none` again, so that the buttons are completely non-interactable (that's not a word, but interactive isn't the right word so I made one up). The no-symbol cursor is for some reason completely obnoxious when you're sliding the mouse around and that cursor flashes on and off as you move your mouse over the disabled buttons.

**Comment by grady404** [comment]
Edit: I honestly think the disabled buttons just shouldn't be shown at all. It would make the interface look a lot more streamlined.

**Comment by cooperuser** [comment]
Fixed!

**Comment by grady404** [comment]
Cool

**Comment by grady404** [comment]
Wait... did you remove the buttons entirely?

**Comment by cooperuser** [comment]
no?

**Comment by cooperuser** [comment]
should I?

**Comment by cooperuser** [comment]
<img width="834" alt="screen shot 2016-09-09 at 7 35 50 pm" src="https://cloud.githubusercontent.com/assets/21961037/18407413/a50e98a4-76c4-11e6-8ede-cd580a791fab.png">
.....?

**Comment by grady404** [comment]
Oh hmm, it looks stranger than I was expecting, but it'll probably look better when you change the buttons to arrows. Don't do it yet, consider this issue closed, but when you make the buttons arrows you should do it.

**Comment by grady404** [comment]
Actually, why don't you just make it a preference somewhere (you can make the system temporary for now, no need to make it fancy)

**Comment by cooperuser** [comment]
Okay

**Comment by grady404** [comment]
Just make a `preferences.json` somewhere
