### ISSUE TITLE
Advance to the next level after completing a level

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#3]
Instead of returning to the level select screen upon completion of a level, advance directly to the next level (if there is one - make sure this doesn't create a bug on completion of the last level). If there are any "holes" - for example, level13 and level15 exist but level14 doesn't - this feature should simply skip right over the holes to the next available level.

**Comment by cooperuser** [comment]
Fixed in version.... (new issue... add correct version labeling)

**Comment by grady404** [comment]
You added it already?
