### ISSUE TITLE
Display level name and number in play mode

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#4]
Use the "name" attribute in the level file (under "data") to display the level name and number within the play screen. I suggest displaying it in the bottom left corner, the number followed by the name, with the number in a little circle (EDIT: see comment below) to make it look nicer. Example: "⓬ Jailbreak". I'd say white with gray text (same as background color) for the circle and white text for the level name, don't know how you'd exactly make the circle, but I trust you'll be able to. And obviously, make everything Hasklig.

**Comment by cooperuser** [comment]
<img width="852" alt="screen shot 2016-09-07 at 8 09 06 pm" src="https://cloud.githubusercontent.com/assets/21961037/18335797/0582ed8c-7537-11e6-8ad6-5bd54a030528.png">

**Comment by grady404** [comment]
Did you also forget to get rid of "test" at the bottom? haha

**Comment by grady404** [comment]
But- you're not actually going to use the unicode characters, right? Because there are only finitely many of those...

**Comment by grady404** [comment]
You know what? I would actually use a rounded rectangle instead of a circle, that way it will display correctly no matter how many digits are in the level number. That will also make it easier for you to implement.

**Comment by grady404** [comment]
I mean circle, not square.

**Comment by cooperuser** [comment]
Have you gotten to a point in adding your levels where you think we should merge the branch?

**Comment by grady404** [comment]
Let me extract the current branch so I can sort through it and see what's in there, and once I do I would just recommend replacing the old branch with the new one including the user levels (don't do it yet though).

**Comment by cooperuser** [comment]
Let me know when, cause merging the two is as simple as pressing a button and the only changes that will be made to the `master` branch are only the changes you made in `levels-main`

**Comment by grady404** [comment]
Yeah but I think you should completely REPLACE the level directory, as
opposed to merging the two versions (which would imply keeping files from
both), but like I said not yet, I'm trying to figure out how to download
the directory

**Comment by grady404** [comment]
I like where you're going with this, but I think the bottom left corner of the screen is too cluttered. You don't need to show the creators _inside_ of the level, show that on the level select screen. And instead of having separate lines for each thing, just make it something like this: `<button [whatever button stuff you do to make it look nice]>NUM</button> Level Name`

**Comment by cooperuser** [comment]
Makes sense, I'll do that

**Comment by cooperuser** [comment]
ooh!! bootstrap labels!

**Comment by cooperuser** [comment]
<img width="359" alt="screen shot 2016-09-07 at 10 40 27 pm" src="https://cloud.githubusercontent.com/assets/21961037/18338235/18dba5bc-754c-11e6-9ab8-e3e15b79d4a0.png">

**Comment by cooperuser** [comment]
any particular color?

**Comment by grady404** [comment]
Oh yeah, of course. Those would look really nice. I'd go with info (that's the same color as the blocks right?)

**Comment by cooperuser** [comment]
indeed

**Comment by grady404** [comment]
Then that for sure

**Comment by grady404** [comment]
Minor thing, upon completing the last available level the "Continue" button shouldn't be disabled, it should just take you back to the level select when you click it

**Comment by cooperuser** [comment]
<img width="816" alt="screen shot 2016-09-07 at 10 43 24 pm" src="https://cloud.githubusercontent.com/assets/21961037/18338312/891eb27e-754c-11e6-9c13-b106c6a2d0dc.png">

**Comment by grady404** [comment]
YES! That looks great. The game already seems a lot more complete

**Comment by cooperuser** [comment]
yeah definitely!

**Comment by cooperuser** [comment]
ooh! a thing we should add to the todo list, fix all the `TODO` things

**Comment by cooperuser** [comment]
(but that doesnt belong in this thread)

**Comment by grady404** [comment]
I'll add that haha

**Comment by cooperuser** [comment]
k good

**Comment by cooperuser** [comment]
So would you say that considers this thread closed?

**Comment by grady404** [comment]
Yep, soon as you add it to the repo.

**Comment by cooperuser** [comment]
awesome

**Comment by grady404** [comment]
Did you do my "minor thing"? ^^^
