### ISSUE TITLE
Finished "Designing" a Version Management System

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#42]
# Semantic Versioning!

If you do not know what this is, you can find it [here](http://semver.org/).
Essentially, it works like this. The version would be in the format: `vX.Y.Z` where `X` is the major version, `Y` is the minor version, and `Z` is the patch version. These values get incremented based on different changes in the API. Every time a bug is fixed you increment the `Z` value, while every time you implement a new feature you increment the `Y` value, and every time you implement a new "non-backwards compatible" feature you increment the `X` value.

I am still debating if I should redo the system we have now, or just continue to keep the numbers the same, but from now on use this new, better system.

**Comment by grady404** [comment]
`A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.`

This is exactly what I was saying about having a fourth digit

**Comment by grady404** [comment]
That fourth digit would only be for the prerelease versions however. I think you should change that
