### ISSUE TITLE
Blank Level in Open Menu in Level Editor

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#43]
I noticed this bug a while ago, pretty self explanatory but sometimes there is an extra first level to choose from thats name is empty

**Comment by grady404** [comment]
So the levels on the first page would be `[ ], [1], [2]...` all the way up to `[15]`? As opposed to `[1], [2], [3]...` up to `[16]`

**Comment by cooperuser** [comment]
no, on the open screen in the editor

**Comment by cooperuser** [comment]
got it to happen again:

**Comment by cooperuser** [comment]
<img width="834" alt="screen shot 2016-09-10 at 12 48 12 pm" src="https://cloud.githubusercontent.com/assets/21961037/18413161/e054ffe4-7754-11e6-9d51-6e97506a52d8.png">

**Comment by grady404** [comment]
Huh, weird. Could it have something to do with one of the hidden files in that directory? Because hidden files always start with a `.` and I assume you're stripping the file from the `.` on. But it seems strange that it only happens occasionally.

**Comment by cooperuser** [comment]
of course!!!

**Comment by cooperuser** [comment]
the `.DS_STORE` on macs!

**Comment by grady404** [comment]
You might at least consider checking to make sure the file name doesn't start with a `.` before you list it, and see if that fixes the bug.

**Comment by grady404** [comment]
But isn't that file _always_ there?

**Comment by cooperuser** [comment]
I can go fix it now

**Comment by grady404** [comment]
Actually you should make sure that's even the problem first, just get rid of the part where it strips the file extension and see if you can trigger the glitch (then you'd see the exact name of the file)

**Comment by cooperuser** [comment]
confirmed:
<img width="841" alt="screen shot 2016-09-10 at 1 16 36 pm" src="https://cloud.githubusercontent.com/assets/21961037/18413306/d55c96f2-7758-11e6-8fda-11d0107be2dd.png">

**Comment by grady404** [comment]
Aha ok just check to make sure the file name doesn't begin with a `.` and if it does remove the dot and everything after it

**Comment by cooperuser** [comment]
It works now, and it also works if you start the level with a `.`, It just saves it like that

**Comment by cooperuser** [comment]
and it loads fine

**Comment by grady404** [comment]
How did you achieve that? Will other hidden files show up by accident with that solution?

**Comment by cooperuser** [comment]
there shouldn't be any other hidden files though

**Comment by cooperuser** [comment]
``` JavaScript
if (files[i] != ".DS_Store") {
    levelName = files[i].split('.')
    levelName.pop();
    levelName = levelName.join('.');
    $("#selectBox").append(`<option>${levelName}</option>`)
}
```

**Comment by grady404** [comment]
Doesn't Mac OS automatically make any files beginning with a dot hidden? In that case you shouldn't even allow players to make a level name start with a dot.

**Comment by cooperuser** [comment]
No, it doesn't do that? I'm pretty sure all system-created files created by the kernel starting with a `.` are hidden

**Comment by cooperuser** [comment]
wait.... your right

**Comment by cooperuser** [comment]
i just checked

**Comment by cooperuser** [comment]
wait... by using those methods we can make the default levels hidden

**Comment by grady404** [comment]
Why would we do that...?

**Comment by cooperuser** [comment]
to stop modding?

**Comment by grady404** [comment]
Uh.... why don't you just _encrypt_ them?

Making them hidden would hardly do anything for people who know a thing or two about computers...

**Comment by grady404** [comment]
And for alpha and beta, I think they should be left editable

**Comment by cooperuser** [comment]
Good point

**Comment by grady404** [comment]
Isn't this closed?
