### ISSUE TITLE
Create better Level 3

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#44]
I think I have a pretty good one, tell me what you think. If it is to your satisfaction, consider this issue closed. Make sure it's easy enough for a new player to understand.
[level3.json.txt](https://github.com/cooper-anderson/Blockade/files/465735/level3.json.txt)

**Comment by cooperuser** [comment]
Yeah this is better, I just think that it is still a bit hard for level 3

**Comment by grady404** [comment]
You do? Oh well. We should probably get some playtesters before we jump to that conclusion, since they might actually appreciate that the game jumps right into the challenge (unlike a lot of other comparable puzzle games), as long as the level isn't hard enough to make them give up. In addition to the old level 3 being difficult-ish, I actually found a design flaw in it, which is a very bad thing (while difficulty isn't necessarily a bad thing). It wouldn't be considered a flaw for a later level, but the thing is, the player doesn't know that blocks can stop other blocks yet (i.e. that they won't stick together like light blocks would), and the player pretty much needs to know that to complete the level, unless they're prepared for a lot of trial and error.

**Comment by grady404** [comment]
I'm going to mark this as closed for now, unless playtesters complain that the level is too difficult.

**Comment by grady404** [comment]
Crap. Making a level that _does_ teach them that is actually very difficult.

**Comment by cooperuser** [comment]
I know, I had Ken play the game yesterday, and when he got to the old third level, he was stuck for quite a bit

**Comment by grady404** [comment]
Yeah, now I realize why

**Comment by grady404** [comment]
The one that's now called `Doubles`, not the one that's now called `Amorphous`, right?

**Comment by grady404** [comment]
Because `Amorphous` used to be level 3, I showed it to you in class and you said it was WAY too hard

**Comment by cooperuser** [comment]
No it was `Doubles`

**Comment by grady404** [comment]
Yeah I figured, and I now realize that level is also too difficult for a Level 3 due to its poor design

**Comment by cooperuser** [comment]
If got it!

**Comment by cooperuser** [comment]
we take `First Steps`, add a `tile` in the top right corner, and place another `block`

**Comment by grady404** [comment]
???

**Comment by grady404** [comment]
Oh um ok let me try that

**Comment by cooperuser** [comment]
Here ill post a screenshot in a minute

**Comment by grady404** [comment]
Personally I think that's way too easy for a level 3. A lot of these puzzle games have super shallow difficulty curves, and people get tired of easy tutorial levels

**Comment by cooperuser** [comment]
<img width="815" alt="screen shot 2016-09-10 at 8 16 24 pm" src="https://cloud.githubusercontent.com/assets/21961037/18414946/7e261648-7793-11e6-96c8-23c555e6e94a.png">

**Comment by grady404** [comment]
But for that level they pretty much need to know that blocks can stop blocks, the level doesn't _teach_ them  that.

**Comment by cooperuser** [comment]
no?

**Comment by grady404** [comment]
How would it?

**Comment by grady404** [comment]
They'll just kind of slide the blocks around and be stuck for a while, unless they happen to move Block B left as their first move.

**Comment by cooperuser** [comment]
They would realize that they wont be able to do anything, and try to do new things

**Comment by grady404** [comment]
Well, you could argue that would happen in `Doubles`

**Comment by cooperuser** [comment]
but `Doubles` was way harder

**Comment by grady404** [comment]
But actually, I like that idea of trying things... so I think I'm going to see how the playtesters do with `Doubles` (under a different name) as their fourth level

**Comment by grady404** [comment]
No, isn't this harder than `Doubles`? Try to beat it

**Comment by cooperuser** [comment]
Shouldn't level four teach them that all plates need to be on?

**Comment by grady404** [comment]
That's um... that would be `Correspondence` (although I might use a different level to teach that if playtesters don't perform well with that one)

**Comment by grady404** [comment]
`Correspondence` is actually level 7 (it's also the first level with 3 blocks)

**Comment by cooperuser** [comment]
<img width="812" alt="screen shot 2016-09-10 at 8 23 09 pm" src="https://cloud.githubusercontent.com/assets/21961037/18414961/6b24ba80-7794-11e6-8150-abd389047d34.png">

**Comment by grady404** [comment]
Level 1: Blocks slide until they hit a wall
Level 2: Blocks must stay on top of plates
Level 3: Blocks can be used together
Level 4: Blocks can't be pushed by other blocks
Level 7: All plates must be activated to win

As far as I know those are the only important things the player needs to know... can you think of any more?

**Comment by cooperuser** [comment]
I changed it a bit, now there is no shuffling

**Comment by grady404** [comment]
That level looks better, but it would be nicer if the design were a bit more streamlined (maybe make the main area smaller)?

**Comment by grady404** [comment]
And isn't there a key command to screenshot a window?

**Comment by cooperuser** [comment]
oh yeah...

**Comment by grady404** [comment]
`Command+Shift+4` then hit space

**Comment by cooperuser** [comment]
yup ....

**Comment by grady404** [comment]
^^^ you can't think of any more core mechanics the player needs to know, right?

**Comment by cooperuser** [comment]
At this point in time, no

**Comment by grady404** [comment]
Oh btw do you have a good idea for a new name for `Doubles`? I can't call it that anymore because Level 3 is `Doubling Up`...

**Comment by cooperuser** [comment]
![screen shot 2016-09-10 at 8 27 46 pm](https://cloud.githubusercontent.com/assets/21961037/18414976/0c7303ec-7795-11e6-8bec-e915ebf2fcae.png)

**Comment by grady404** [comment]
To use Excel terminology, why is there a tile at C5?

**Comment by grady404** [comment]
Btw I think this is way harder than `Doubles`

**Comment by cooperuser** [comment]
To stop the player from moving F4 to C4 to C2, and then B4 to F4, then C2 to C4, then F4 to D4 to the goal

**Comment by cooperuser** [comment]
By the way, as far as I can tell, this level is 12 moves

**Comment by cooperuser** [comment]
11 in that picture, 12 in the final version I updated

**Comment by grady404** [comment]
Block B left
Block B down
Block A up
Block A right
Block B up
Block A left
Block A up

**Comment by grady404** [comment]
Then you don't have to go through the tunnel

**Comment by cooperuser** [comment]
damn..

**Comment by grady404** [comment]
wait, that's actually a great level on its own LMFAO

**Comment by grady404** [comment]
Move block A one square to the left and delete the tunnel

**Comment by grady404** [comment]
But keep the block in F5

**Comment by cooperuser** [comment]
![screen shot 2016-09-10 at 8 33 12 pm](https://cloud.githubusercontent.com/assets/21961037/18414988/ce8be5ac-7795-11e6-8ed0-d71eda66a368.png)

**Comment by grady404** [comment]
You have to add E5 back (not F5, oops). And why not remove F1 and add G4, and call it `Flying Saucer` or something?

**Comment by grady404** [comment]
And stick the second block in G4 to make it symmetrical (and harder).

**Comment by cooperuser** [comment]
![screen shot 2016-09-10 at 8 36 42 pm](https://cloud.githubusercontent.com/assets/21961037/18414996/4b9c84c0-7796-11e6-9a4a-726d6494c047.png)

**Comment by cooperuser** [comment]
10 moves?

**Comment by grady404** [comment]
Checking that...

**Comment by cooperuser** [comment]
oh! and the thing thats great about this is that it **forces** the person to learn that they collide in the  first move

**Comment by grady404** [comment]
oh wait yeah! You're right! I actually wasn't going to make this level 4, but it might work as that

**Comment by grady404** [comment]
Yeah I can't beat 10 moves, so I guess that's that

**Comment by grady404** [comment]
I will recreate the level and add it to the level package

**Comment by grady404** [comment]
Or actually, just attach it to a comment

**Comment by cooperuser** [comment]
awesome, lets head over to #6 and see if we need to change anything about how your proposed file organization system looks.

**Comment by grady404** [comment]
Alright. Send me the level and I'll be right over

**Comment by cooperuser** [comment]
[level3.json.zip](https://github.com/cooper-anderson/Blockade/files/465762/level3.json.zip)
heres this btw

**Comment by grady404** [comment]
[grady-doubling-final.json.zip](https://github.com/cooper-anderson/Blockade/files/504072/grady-doubling-final.json.zip)

Thoughts for level 3?

**Comment by cooperuser** [comment]
7 moves?

**Comment by grady404** [comment]
Yeah, why? Do you think it's good for a level 3?

**Comment by cooperuser** [comment]
Wasnt this a big jump from difficult to easy?

**Comment by grady404** [comment]
Too easy?

**Comment by cooperuser** [comment]
Hmm... I still think this is better than the previous one though

**Comment by grady404** [comment]
Sadly, there doesn't really seem to be much of a middle ground between this and the current level 3, considering I can't require one of the blocks to stop another block (which isn't taught until level 4)... I messed around and was only really able to make it bigger, which makes it _look_ harder but doesn't actually add any challenge gameplay-wise.

**Comment by cooperuser** [comment]
Hmm...

**Comment by grady404** [comment]
Here's one possibility that requires slightly more thought:

![screen shot 2016-09-30 at 7 59 43 pm](https://cloud.githubusercontent.com/assets/10258414/19011389/793ae2ca-8748-11e6-9b84-05440a057476.png)

**Comment by grady404** [comment]
Think I might have a final Level 3 design:

![screen shot 2016-10-01 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/10258414/19016549/20f717f2-87d2-11e6-933f-ac0d1d511994.png)

It's the same idea as the current Level 3, but with a lot of the excess blocks stripped away to make the level more direct, and easier to understand.

**Comment by cooperuser** [comment]
Yeah I think this one looks good.

**Comment by grady404** [comment]
Alright. I guess this means I'll have to make the current Level 3 an outtake, since this level is a modification of that, rather than an entirely new level. Maybe we can include the "lost levels" somewhere with the bonus levels (where the Zelda levels will be).

**Comment by cooperuser** [comment]
Hmm... Maybe we could do anything like that

**Comment by grady404** [comment]
The only (extremely minor) problem with this level is it's not very good at teaching players that blocks can collide with other blocks, although I don't think this is a problem at all since 99.9% of players will infer that, rather than thinking that blocks go through each other or something weird like that.

**Comment by cooperuser** [comment]
Yeah, but it does show they have to collide the blocks to even get to the end

**Comment by grady404** [comment]
True, but if for some insane reason the player didn't realize that blocks could collide with each other, it might take them a while for them to realize how they work

**Comment by grady404** [comment]
Off topic, I came up with a cool new gameplay mechanic... I'll make a new issue for it

**Comment by cooperuser** [comment]
Awesome, I'll check it out when you do it

**Comment by grady404** [comment]
What do you think of making Level 3 one block larger, like so?

![screen shot 2016-10-02 at 3 00 39 pm](https://cloud.githubusercontent.com/assets/10258414/19024076/2421b7fe-88b1-11e6-991c-b8ee9c1e4095.png)

It gives the player more room to experiment with multiple blocks, and it eliminates the problem I mentioned of the player not being able to learn how blocks collide with each other, but this design might also make the puzzle appear more difficult. Yes or no?

**Comment by cooperuser** [comment]
Yeah I think this one is good. 6 moves?

**Comment by grady404** [comment]
Yeah. I showed this one to my brother (him not having seen the original 4x4 version) and he was able to beat it just fine. But when he got to Saucer that was a different story (although he was also on a limited attention span–we'll see what our actual playtesters think of it)

**Comment by cooperuser** [comment]
Okay
