### ISSUE TITLE
Level Flags

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#47]
This feature will be built into the overhaul of the game. But essentially, what it is, is a list in the level `JSON` that would contain strings. An example of what one of these strings could be is "showMoveButtonsOnLoad" (name subject to change). What this would do is anytime the player sees a level with this flag, it makes it so the block buttons show up automatically. There can be a variety of different flags.

**Comment by grady404** [comment]
The `showMoveButtonsOnLoad` (or whatever you chose to call it) flag does not seem to be implemented.

**Comment by cooperuser** [comment]
The specific `showMoveButtonsOnLoad` flag is not implemented, but the `flags` feature itself is.

**Comment by grady404** [comment]
You didn't "implement" anything by adding some non-functional text in the JSON, so don't mark this closed until the actual flag (the only one we should really care about at the moment) is implemented.

**Comment by grady404** [comment]
Did you see my new issue?
