### ISSUE TITLE
Make the level select header non-clickable

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#5]
This is pretty dumb, but the page header in the level select screen is technically a button, and you should probably disable it or whatever, so it's not clickable. Edit: Just looked at one of my old CSS files, and the CSS property is "pointer-events: none".

**Comment by cooperuser** [comment]
This issue... isn't really an issue.. but ill fix anyway

**Comment by grady404** [comment]
They don't really have to be issues per se, GitHub's placeholder text just
told me it was for "features, suggestions, bugs, etc."
