### ISSUE TITLE
Level JSON structure

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#52]
So I thought about the two different versions of the wiring system for a while, and realized that if you have a lot of inputs/outputs in the same area (for example, if you wanted to make a level that was a maze of doors) it would be impossible to do so using the grid-based wiring system. For this reason I _really_ think you should use the Starbound-esque wiring system, as it would allow for much greater flexibility when creating compact wiring systems. And because of that, I think you should keep the JSON files in a format similar to what they are now, so that you can set the start and end points of wires right next to each other, and wouldn't have to use wire IDs or something weird like that to connect the two points. No, this doesn't go against the entire overhaul, I think the way the objects are stored in-game is fine, but as far as the way objects are saved to the JSON files, I think it should be more similar to how it is currently. So forget the example JSON I AirDropped to you in class; I'll make a new example JSON, and upload it here as soon as I can.

**Comment by grady404** [comment]
Alright, here's the new [`example.json`](https://github.com/cooper-anderson/Blockade/files/468798/example.json.txt).
A few things you might consider changing about it:
- Merge the `Block` category into the `BlockGroup` category, and simply call the new category `Block`. Treat singular blocks as block groups of size 1.
- Change some of the arrays to dictionaries. Examples: Change `[[2, 1], "Standard.Blue"]` to `{"position": [2, 1], "subclass": "Standard.Blue"}`, or change `[[3, 1], "output0"]` to `{"position": [3, 1], "connection": "output0"}`.

**Comment by grady404** [comment]
Here's the final [`example.json`](https://github.com/cooper-anderson/Blockade/files/473604/example.json.txt). You don't need to worry about _everything_ in here for now. I'll upload another `example.json` that only shows you the stuff you need to worry about right now.

**Comment by grady404** [comment]
Here's [`example-simple.json`](https://github.com/cooper-anderson/Blockade/files/473727/example-simple.json.txt), a simplified version of `example.json`. This is all you should focus on implementing for now. Note that if any of the variables in the `data` section are missing (e.g. `name`, `creators`, `creator-score`, and `flags`) the game is prepared to handle that.

**Comment by cooperuser** [comment]
[new2.json.zip](https://github.com/cooper-anderson/Blockade/files/475676/new2.json.zip)
Here, check out this idea. It uses a hybrid of both of our systems by having a list of each object, but it has a variable for the `class` and `attribute`, where you would enter all other details. I am still considering if I should have the `position` variable not be under the `attribute` variable though.

**Comment by grady404** [comment]
Hmm... I do like where you're going with that, with the attributes and all, but there are a few problems. First of all, it's not compact enough - I designed my version so that each individual object would be as compact as possible. That's why I like `"position": [0, 0]` better than `"position": {"x": 0, "y": 0}`. I also don't think `position` should be an `attribute`, since attributes determine characteristics _about_ an object, not information about its position. To put it in non-programming terms, the fact that I have blond hair is an attribute of me, while the fact that I am in my bedroom right now is not. Also, position is something an object _must_ have, while attributes are not (hollow blocks don't need a specified color, for instance).

To make it more compact, I think the `color` attribute should correspond to a number, not a string. `0` would signify blue, `1` would signify red, `2` would signify green, and `3` would signify orange. In fact, there's another reason I think we should do this besides compactness - what if one of the themes we implement later (see #15) has different colors of blocks/plates/switches? The "main" block color might be purple in one of the themes, and all the block colors might be in a different order, so it makes more sense to simply denote it as a number.

The `rotation` and `state` attributes would also be numbers. The `state` attribute would either be `0` for disabled, or `1` for enabled. The `rotation` attribute would depend on the object. If the object has four-way rotational symmetry (like a block, plate, or the letter O), there would be no `rotation` attribute at all. If an object has two-way rotational symmetry (like the letter H), `rotation` would either be set to `0` or `1`. If it has no rotational symmetry (like the letter A), `rotation` could be `0`, `1`, `2`, or `3`, with each new number rotating the object clockwise by 90 degrees.

So here's the final block object for reference:
`{"class": "Standard", "position": [0, 0], "attributes": {"color": 0}}`

There are a couple more problems down at the bottom of the JSON - first of all, where did the `data` section go? Now those variables are all just piled into a jumbled mess down there... Anyway, the `size` variable needs to go, completely. _You don't need it there._ You can determine the size of the level without a specific variable for it, simply by looking at the positions of all the objects on the board and taking the maximum x and y values. Also, "par" is a defunct idea now, since there are two scores (`moves` and `distance`). If you look at my `example.json` above, you'll see that I combined them into something that looks like this: `"creator-score": {"moves": 8, "distance": 27}`. I called it `creator-score` because the creator(s) of a level won't know for sure that that's the minimum amount of moves needed to complete the level, so it becomes a sort of challenge for people playing a level to beat the creator's score. Anyway, you should see the `data` section of my `example.json` for an idea of what it should look like.

**Comment by cooperuser** [comment]
I agree with the whole `position` part not being in `attribute`, and the `rotation` part. About the stuff at the bottom of the `JSON`, I like not having the whole `data` part, I think it makes it less intuitive because, I mean, its all data... Also I think that `par` is a better name than `creator-score` because it IS the par, pars aren't supposed to be unbeatable, Also are these values going to be changing if the score is beaten? if not then I guess both `par` and `creator-score` are good names.

**Comment by grady404** [comment]
I think `rotation` _should_ be an attribute (unlike `position`), since it sorta corresponds to how the object behaves.

And yes, there is one difference between a par and a creator score - a creator score is the best score the creator could possibly get, whereas a par kind of implies that it was just some score that they felt would be good for players to shoot for. For example, the creator could beat the level in nine moves, but think "it was really hard to do that in nine moves, I think 12 moves would be a better par" and set the par to 12 moves. A creator score is different; if the creator beat the level in nine moves, then the creator score would be nine moves, period. I like the creator score system better than the par system because it challenges the players to beat the score of the creator, rather than beating some arbitrary score (which in most cases probably wouldn't even be that hard to beat).

And I think it would be weird not to include the `data` section at the bottom of the JSON, since it separates those values from the values that make up the board's structure. It's weird in the same way that storing the user levels in a subdirectory of the default level directory was (back before you reorganized the game's files). But I agree that "data" probably isn't the best word for that section. Maybe `info`, or `details`?

**Comment by cooperuser** [comment]
I agree that `rotation` should be an attribute. And now that you have elaborated on the `creator-score` thing it makes a lot more sense to go with your methods. And for the `data` part, in code it makes sense for it to be `level.board` and `level.grid`, but `level.data.name` or `level.details.name` doesn't really make as much sense as `level.name`. These names would be better because if anyone were to make a new `block` or `plate`, interacting with the level would be more intuitive.

**Comment by grady404** [comment]
What did you mean with that last sentence?

And I would definitely prioritize ease of user experience over ease of programming. The way the JSON is organized is something the user will actually see, whereas the way it is coded isn't. And I personally think `level.data.name` or `level.info.name` is perfectly fine.

**Comment by cooperuser** [comment]
The user will be seeing the `JSON`?

**Comment by grady404** [comment]
Yeah, why not? There's nothing wrong with them screwing with the level files, as long as they can't upload broken levels to the sharing service (we'll use encrypted certificates to fix that)

**Comment by cooperuser** [comment]
Hmm...

**Comment by cooperuser** [comment]
I'm not too sure, but I still think that

``` JSON
"name": "Test Level",
"creators": ["Cooper Anderson", "Grady Shoemaker"],
"creator-score": {
    "moves": 8,
    "distance": 27
}
```

is better than

``` JSON
"info": {
    "name": "Test Level",
    "creators": ["Cooper Anderson", "Grady Shoemaker"],
    "creator-score": {
        "moves": 8,
        "distance": 27
    }
}
```

**Comment by grady404** [comment]
If you're giving someone a watermelon and a bunch of grapes, do you put them all in the same bag? Or do you put all the grapes in one bag, and then hand that to them alongside the watermelon?

**Comment by cooperuser** [comment]
Yeah but... These aren't grapes...

**Comment by cooperuser** [comment]
Neither of these things are very different coding wise, I just think that not having another subobject makes things simpler coding wise.

**Comment by grady404** [comment]
`name`, `creators`, `creator-score`, and `flags` are the grapes. `grid`/`board` is the watermelon. (I think you should call it board btw.)

**Comment by grady404** [comment]
But JSON-wise, I think it makes much more sense to put all the "grapes" in their own container. Think about it: there will only be one JS file with the code in it, there will be hundreds and hundreds of level JSON files.

**Comment by cooperuser** [comment]
Yeah I did end up calling it `board` but I made that change after I sent the file

**Comment by cooperuser** [comment]
I guess we could go with your method, If we ever need to change it, it wouldn't be the hardest thing to change anyway

**Comment by cooperuser** [comment]
But we should not use `data` as the keyword, because everything in the file is `data`

**Comment by grady404** [comment]
Yeah, that's why I proposed `info` instead. I realized `data` was a terrible name

**Comment by cooperuser** [comment]
`info`, `details`, any others?

**Comment by grady404** [comment]
The only other useful synonym I could find was `attributes`, but we already used that for the attributes of each object within the level. I like `info`, because `level.info.name` for instance sounds cleaner than `level.details.name`.

**Comment by cooperuser** [comment]
Yeah, I guess we will go with `info` then

**Comment by grady404** [comment]
<img width="494" alt="screen shot 2016-09-15 at 7 14 36 pm" src="https://cloud.githubusercontent.com/assets/10258414/18573477/ade13406-7b78-11e6-95c4-362e2f983948.png">

`level.poop.name`
`level.poop.creator-score`
`level.poop.flags`

**Comment by grady404** [comment]
`level.dope.creators`

**Comment by cooperuser** [comment]
what!?!?!

**Comment by grady404** [comment]
Don't ask me...

**Comment by grady404** [comment]
anyway, there aren't a whole lot of useful synonyms in there. `info` would be our best choice

**Comment by cooperuser** [comment]
Yeah

**Comment by grady404** [comment]
What else do you need to do to finish the overhaul?

**Comment by cooperuser** [comment]
Hmm.. Right now I need to implement an efficient way of rendering the game.

**Comment by cooper-anderson** [comment]
Btw the new format for the `JSON` is:
```JSON
{
  "grid": {
	"Tiles": [
	  {"class": "Standard", "position": [0, 1]},
	  {"class": "Standard", "position": [0, 2]},
	  {"class": "Standard", "position": [0, 3]},
	  {"class": "Standard", "position": [1, 1]},
	  {"class": "Standard", "position": [1, 2]},
	  {"class": "Standard", "position": [1, 3]},
	  {"class": "Standard", "position": [2, 1]},
	  {"class": "Standard", "position": [2, 2]},
	  {"class": "Standard", "position": [2, 3]},
	],
	"Plates": [
	  {"class": "Standard", "position": [1, 1], "attributes": {"color": "blue"}}
	],
	"Blocks": [
	  {"class": "Standard", "position": [0, 2], "attributes": {"color": "blue"}}
	],
	"Gates": [

	],
	"Wiring": [

	]
  },
  "info": {
	"name": "Debug",
	"creators": [
	  "Cooper Anderson"
	],
	"par": -1,
	"flags": [],
	"size": {
	  "x": 3,
	  "y": 3
	}
  }
}
```

**Comment by grady404** [comment]
Wrong file...

**Comment by cooperuser** [comment]
oops that wrong hang on

**Comment by cooperuser** [comment]
```
{
  "grid": {
    "Tiles": [
      {"class": "Standard", "position": [0, 1]},
      {"class": "Standard", "position": [0, 2]},
      {"class": "Standard", "position": [0, 3]},
      {"class": "Standard", "position": [1, 1]},
      {"class": "Standard", "position": [1, 2]},
      {"class": "Standard", "position": [1, 3]},
      {"class": "Standard", "position": [2, 1]},
      {"class": "Standard", "position": [2, 2]},
      {"class": "Standard", "position": [2, 3]}
    ],
    "Plates": [
      {"class": "Standard", "position": [1, 1], "attributes": {"color": "blue"}}
    ],
    "Blocks": [
      {"class": "Standard", "position": [0, 2], "attributes": {"color": "blue"}}
    ],
    "Gates": [

    ],
    "Wiring": [

    ]
  },
  "info": {
    "name": "Debug",
    "creators": [
      "Cooper Anderson"
    ],
    "creator-score": {
      "moves": -1,
      "distance": -1
    },
    "flags": []
  }
}
```

**Comment by grady404** [comment]
A few minor things...
- `board`, not `grid`, remember?
- Get rid of the empty lists for `Gates` and `Wiring`
- Use the singular names for `Tile`, `Plate`, and `Block`, because those are actually the names of the respective classes
- Put `creators` and `creator-score` on one line rather than spaced out across multiple. Example: `"creators": ["Cooper Anderson", "Grady Shoemaker"]`, and `"creator-score": {"moves": 7, "distance": 29}`. This one doesn't actually affect the way the JSON is loaded but makes it look cleaner.

**Comment by cooperuser** [comment]
Oh yeah... this wasnt the version where i renamed it to `board`

**Comment by cooperuser** [comment]
Should we get rid of the empty `flags` variable?

**Comment by grady404** [comment]
Yeah I do think so actually, if the level doesn't have any flags there shouldn't be an empty list there. I would also make it so that your game is equipped to handle the lack of any other `info` variables (`name`, `creators`, etc.)

**Comment by cooperuser** [comment]
Yeah, of course

**Comment by grady404** [comment]
And why the -1 creator scores? If there isn't a creator score, don't have that object there

**Comment by cooperuser** [comment]
New and improved:

``` JSON
{
  "board": {
    "Tiles": [
      {"class": "Standard", "position": [0, 1]},
      {"class": "Standard", "position": [0, 2]},
      {"class": "Standard", "position": [0, 3]},
      {"class": "Standard", "position": [1, 1]},
      {"class": "Standard", "position": [1, 2]},
      {"class": "Standard", "position": [1, 3]},
      {"class": "Standard", "position": [2, 1]},
      {"class": "Standard", "position": [2, 2]},
      {"class": "Standard", "position": [2, 3]}
    ],
    "Plates": [
      {"class": "Standard", "position": [1, 1], "attributes": {"color": "blue"}}
    ],
    "Blocks": [
      {"class": "Standard", "position": [0, 2], "attributes": {"color": "blue"}}
    ]
  },
  "info": {
    "name": "Debug",
    "creators": ["Cooper Anderson"],
    "creator-score": {"moves": -1, "distance": -1}
  }
}
```

**Comment by cooperuser** [comment]
but this level is impossible

**Comment by cooperuser** [comment]
It is purely for showing this

**Comment by grady404** [comment]
Oh this is the impossible one, didn't realize that

**Comment by cooperuser** [comment]
Yeah, I should of specified that in the `name`

**Comment by grady404** [comment]
You forgot to use the singular names (`Tile`, `Plate`, etc.)

**Comment by grady404** [comment]
And you forgot to make the color 0 rather than "blue"

**Comment by cooperuser** [comment]
oh yeah,

**Comment by cooperuser** [comment]
But do you think that having `0` instead of `blue` is a good idea?

**Comment by cooperuser** [comment]
(even if we do that I think that `0` should be white)

**Comment by grady404** [comment]
There is no white...?

Are you thinking of hollow blocks?

**Comment by grady404** [comment]
And the reason I think colors should be numbers is that different themes might map the colors differently

**Comment by cooperuser** [comment]
Oh I consider `wildcard` as you call it to be `white`

**Comment by grady404** [comment]
Wildcard should be a completely separate thing.

`{"class": "Standard", "position": [0, 0]}`
`{"class": "Wildcard", "position": [0, 0]}`

**Comment by cooperuser** [comment]
What? no... a completely separate thing?

**Comment by grady404** [comment]
The reason is that wildcard blocks actually behave differently from the other blocks. All Standard blocks have the same fundamental behavior, it's just that they have different numbers that correspond to which plates they can activate. It would be weird if it were like this:

`0` blocks can activate plates that are `0`, `1`, `2`, `3`, `4`, etc.
`1` blocks can activate plates that are `1`
`2` blocks can activate plates that are `2`
`3` blocks can activate plates that are `3`
`4` blocks can activate plates that are `4`

^^^ Spot the inconsistency

**Comment by cooperuser** [comment]
I though there were gonna be colors, then a white one that goes on all

**Comment by grady404** [comment]
Wildcards aren't actually going to be white, I don't think. I think they should kind of look like the Windows logo (best thing I could think of as an example), with each of the four corners a different color so the player kind of intuitively knows what they do from looking at them.

**Comment by cooperuser** [comment]
eh....

**Comment by cooperuser** [comment]
but what if we integrate the `light block`, which could have different colors, and wouldnt that have its own `wildcard`?

**Comment by grady404** [comment]
Trust me, code-wise it will be easier if Wildcards are their own thing.

`if (block.color == plate.color)` (Wildcards separate)
`if (block.color == plate.color or block.color == 0 or plate.color == 0)` (Wildcards = 0)

**Comment by grady404** [comment]
Lightweight blocks shouldn't be able to activate plates at all.

**Comment by grady404** [comment]
If they do, we can have a `Block.Lightweight.Wildcard` in addition to `Block.Standard.Wildcard`

**Comment by cooperuser** [comment]
But what if we do integrate some sort of block that can go on plates, and can be colored, and can have a wildcard... I think that it would be more intuitive if it works with all types of blocks

**Comment by grady404** [comment]
I found a loophole. If lightweight blocks can activate plates, and we thus want different colors of lightweight blocks, and wildcard lightweight blocks... won't we want lightweight _hollow_ blocks too? Then we'd need a color for hollow also... I think this would be easier:

`Block.Standard`
`Block.Standard.Wildcard`
`Block.Standard.Hollow`
`Block.Lightweight`
`Block.Lightweight.Wildcard`
`Block.Lightweight.Hollow`

**Comment by grady404** [comment]
I just realized how dumb this whole "Standard" thing is anyway. Why not just make `Block` the class for standard blocks?

`Block`
`Block.Wildcard`
`Block.Hollow`
`Block.Lightweight`
`Block.Lightweight.Wildcard`
`Block.Lightweight.Hollow`

**Comment by cooperuser** [comment]
Because then we would have the superclass in the game, and that is not good

**Comment by grady404** [comment]
But if we're going to be using `Block.Standard.Wildcard` alongside `Block.Standard` (subclass/superclass), why not just use `Block.Wildcard` and `Block`?

**Comment by cooperuser** [comment]
I do not think that there should be a `Block.Standard.Wildcard` I think that everything that does not have a color, is wildcard, which is default to `white`, or `0`

**Comment by grady404** [comment]
Or else, we'd have to do it like this:

`Block.Standard.Standard`
`Block.Standard.Wildcard`
`Block.Standard.Hollow`
`Block.Lightweight.Standard`
`Block.Lightweight.Wildcard`
`Block.Lightweight.Hollow`

**Comment by grady404** [comment]
I _definitely_ don't think that wildcard should be a color, because the block actually has different behavior when it's a wildcard.

**Comment by cooperuser** [comment]
What kind of different behavior? all it does thats different is it activates all other colors

**Comment by grady404** [comment]
"A block of color `n` can activate all plates and switches of color `n`, and nothing else."

If color `0` denotes a wildcard, it breaks that rule.

**Comment by cooperuser** [comment]
The `O` blood type is considered the donor blood type because it can be used by all other types, but that doesn't make it something that isn't a blood type?

**Comment by cooperuser** [comment]
But what set that rule in the first place?

**Comment by grady404** [comment]
Your code will set that rule, and besides it's better to have things consistent.

**Comment by grady404** [comment]
Besides, if wildcard is a color, why isn't hollow a color? They both relate to which plates and switches the block can and can't press...

**Comment by cooperuser** [comment]
No, `hollow` is its own `block` subclass, completely separate from all colors, and it doesnt interact with colors in any way, the "wildcard" as you called it would be a color because it has the ability to fit all colors.

**Comment by grady404** [comment]
The other problem is it might be confusing for people editing the JSON. Again, "explicit is better than implicit", to quote the Zen of Python. It makes intuitive sense that 0, 1, 2, and 3 would correspond to the four main colors within the game.

**Comment by cooperuser** [comment]
I think that to people who do not know programming, that `1-4` are the main colors and that `0` is the outlier that acts differently

**Comment by grady404** [comment]
Besides, I really don't think `Lightweight` blocks should be able to activate plates. `Lightweight` blocks are meant to be pushed and shoved around to reach other places. It kind of ruins the challenge of `Lightweight` blocks if they're the ones that are supposed to be pressing the plates, not the ones that get shoved around in the process.

**Comment by grady404** [comment]
Oh but we're already using 0, 1, 2, and 3 for rotation, and 0 and 1 for enabled/disabled. If all the other `attributes` begin at zero, it makes perfect sense that this one would too.

**Comment by cooperuser** [comment]
Okay, disregard what I said about `lightweight` blocks

**Comment by cooperuser** [comment]
But that makes sense because it is `0` for no rotation, and `0` for no color, or white

**Comment by grady404** [comment]
Hmm... I don't know. It just seems to make more sense that in most levels, all of the blocks would have color `0`. Blue pretty much is no color, since it's the default, and all other colors are basically variations that only appear in a few specific levels.

**Comment by cooperuser** [comment]
Then why not have `0` as the default color, either make all blocks be white in those levels, or have a scan to see if there are any other colors, and if not, make `0` blue

**Comment by grady404** [comment]
You know, we could always use `-1` for wildcard later, which would make more sense than `0`. Think about it, in Python's `.find()` string function for instance, it returns `-1` if it doesn't find the character. So `-1` is more of a "nonexistent" value than zero is, and it would make more sense that the default color (blue) is `0` rather than `1`.

**Comment by cooperuser** [comment]
But python uses `-1` because if it said `0` that would mean the first index in the character list, and about your argument earlier about having the colors be `0-3`, in this case it would just be `0-4`

**Comment by grady404** [comment]
And like I said, I think wildcards should have all four colors displayed on them, so it's clear what they are. Like the wildcard in the game [UNO](https://www.google.com/search?q=uno+wildcard&espv=2&biw=1920&bih=1099&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjs2cLL8pLPAhVBymMKHb5mDPQQ_AUIBigB#imgrc=p6Zi1oHui2XO-M%3A) for instance

**Comment by grady404** [comment]
And no, the colors would be `-1` to `3`.
- `-1`: wildcard
- `0`: blue
- `1`: red
- `2`: green
- `3`: orange

**Comment by grady404** [comment]
That way, in all the levels that only have one color of block (probably around 80-90 percent of levels) all the blocks would have color `0`, which makes perfect sense.

**Comment by cooperuser** [comment]
Okay, that is a valid argument. However, we have to continue this another time because I have to go somewhere now, I might be able to continue on my phone though.

**Comment by grady404** [comment]
Alright, I kind of wish we had a third person's input to help us decide... whatever though. I would suggest just setting it so that `0` is blue for now, since we won't be adding wildcard blocks for a good while anyway. If need be, we can change it.

**Comment by cooperuser** [comment]
Yeah, good point. Whenever we enter a situation like this I have been asking people for their opinions, I have asked Brad about stuff like this and he usually has done good input.

**Comment by grady404** [comment]
Well anyway, have you actually implemented any of this JSON stuff yet?

**Comment by cooperuser** [comment]
Yeah pretty much everything we have mentioned so far is in the new system so far

**Comment by grady404** [comment]
Oh really? So it's actually implemented?

**Comment by cooperuser** [comment]
The game isn't "playable" yet, but it's functional

**Comment by grady404** [comment]
So I assume all you need to do is get the inner workings of the game to interface with the visuals?

**Comment by cooperuser** [comment]
Yep, that's pretty much it

**Comment by grady404** [comment]
I feel like an idiot... it just dawned on me that I can sum up my entire argument about the color attribute and the wildcard blocks (see above) in one word: "interchangeable". If we were to make wildcard blocks a separate class rather than the same class with `"color": 0`, all of the different block colors would be interchangeable. That's what I was trying to say about the "behavior being the same", I now realize that was an awful way to phrase that.

**Comment by cooperuser** [comment]
Interchangeable? What do you mean by that?

**Comment by grady404** [comment]
So what I proposed is that for blocks, plates and switches, `"color": 0` corresponds to blue, `"color": 1` corresponds to red, `"color": 2` corresponds to green, and `"color": 3` corresponds to orange. Wildcard blocks/plates/switches are their own classes entirely. Using this method, if you created a level using `"color": 0` blocks and `"color": 3` blocks, you could easily switch it to utilize `"color": 1` and `"color": 2`, and the level would work exactly the same. So in a sense all of the colors "work the same", they just don't work the same when you put them together. I don't know if this is a good metaphor for what I'm trying to say, but suppose I say that the north and south ends of a magnet work the same. They don't _really_ work the same, since north attracts to south but not to another north, but they are interchangeable. If you change all norths to souths and vice versa in a system of magnets, that system of magnets would behave the exact same way.

With your system, where `"color": 0` denotes a wildcard, the wildcard color is quite clearly _not_ interchangeable with the other four colors. If you have a color with blue and orange blocks, and you change the colors so that they are now red and wildcard blocks, the level will work differently. Hopefully all this makes sense.

**Comment by cooperuser** [comment]
Yeah, that is what I thought you meant, but after we discussed earlier that we would use `"color": -1` for it that sort of changes this, because it is clear that `-1` is different from `0` to `3`

**Comment by grady404** [comment]
Yeah, that's why I like wildcard being its own class, that makes sense anyway since it will utilize different code

**Comment by cooperuser** [comment]
But by using my method it will require less code, and keep the `JSON` neater.

**Comment by grady404** [comment]
How will it keep the JSON neater? My solution would take up _less_ space in the JSON.

Yours: `{"class": "Standard", "position": [0, 0], "attributes": {"color": 0}}`
Mine: `{"class": "Wildcard", "position": [0, 0]}`

**Comment by grady404** [comment]
And I see where you're coming from with it using less code, but you shouldn't cut code size at the expense of clarity and organization. If you could, you might as well write the entire program in one line.

**Comment by cooperuser** [comment]
Well I guess that "neater" isn't the right word. What I was trying to say is that it would require less things to memorize and understand if the user were to open the `JSON`. And also, what if we later add a new block type that acts differently from normal ones, but we want it to be able to have its own "wildcard" alternative, the only reasonable solution is to make it a color.

**Comment by grady404** [comment]
`Block.WhateverTheNewBlockTypeIs.Wildcard`

**Comment by cooperuser** [comment]
But how is that different from `Block.WhateverTheNewBlockTypeIs.Green`

**Comment by grady404** [comment]
And it would be harder for the user to understand the `"color": 0` being the wildcard just from looking at the JSON. It's not intuitive, whereas `Block.Wildcard` is explicit and it's instantly obvious what it is.

**Comment by grady404** [comment]
Well anyway, even if you were to have wildcard as a color, I think that color would be best off as `-1`, so I would suggest you just make `0-3` the colors for now and decide how to implement wildcard later

**Comment by cooperuser** [comment]
`"color": -1` is wildcard, `"color": 0` is blue

**Comment by cooperuser** [comment]
That is already how it is

**Comment by grady404** [comment]
Alright, we can ask Brad or someone for a third opinion on this, there are obviously pros and cons to each approach

**Comment by cooperuser** [comment]
Yeah I guess so. Hahaha this is usually how all our debates end up
