### ISSUE TITLE
Multiples of 16 Level Select Bug

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#55]
So we _finally_ have enough levels to fill up an entire page, but upon adding the 16th level I noticed a very odd bug occurring in the level select screen. Right after entering the level select or changing pages, if you click on whatever multiple of 16 appears on the page (in the bottom right corner), instead of selecting that level the game will enter whatever level is currently selected. This only happens if it is the first level you select while on that page. Examples:
- Enter level select. Move to Page 2 and select Level 19. Go back to Page 1. Click on Level 16. Instead of selecting Level 16, the game will automatically enter Level 19.
- Enter level select. Immediately click Level 16. The game will attempt to enter whichever level is selected, but since there is no level selected right after entering the level select, nothing will happen. Level 16 will not become selected.
- Enter level select. Click on Level 7, then Level 16. The game will enter Level 16 (the intended behavior) since it was the second, not the first, level you selected while on that screen.
- (This case is a bit stranger.) Enter level select. Click on Level 7. Move the Page 2, then directly back to Page 1. Click on Level 16. Instead of selecting Level 16, the game will automatically enter Level 7. Even though you already had selected another level on the same page (as with the previous example), the behavior was different since you moved over a page and then back again, and Level 16 was the first level you selected after returning to Page 1.

**Comment by cooperuser** [comment]
Is this fixed? I did not do anything specifically to fix it.

**Comment by grady404** [comment]
I fixed it, see my recent commits (I was "exploring" your code)

**Comment by grady404** [comment]
Speaking of, could you give me a developer copy of the game so I have access to the console?

**Comment by grady404** [comment]
I've been using the `alert()` function haha

**Comment by cooperuser** [comment]
`````` Bash
#!/usr/bin/env bash
cd "$(dirname "$0")"/app;
/Applications/Electron.app/Contents/MacOS/Electron ./```
``````

**Comment by grady404** [comment]
``` Bash
Gradys-MBP:~ Grady$ cd "$(dirname "$0")"/app;
dirname: illegal option -- b
usage: dirname path
-bash: cd: /app: No such file or directory
Gradys-MBP:~ Grady$ 
```

**Comment by cooperuser** [comment]
Create a `<name>.sh` file in the same location as the `/app/` directory

**Comment by cooperuser** [comment]
and put

``` Bash
#!/usr/bin/env bash
cd "$(dirname "$0")"/app;
/Applications/Electron.app/Contents/MacOS/Electron ./
```

in it

**Comment by cooperuser** [comment]
And then in terminal run:

``` Bash
chmod a+x <drag in <name>.sh>
```

**Comment by grady404** [comment]
Name as in my name? Or just the name of the file? (What did you call yours)

**Comment by cooperuser** [comment]
Name as in `run.sh` or something

**Comment by cooperuser** [comment]
I called mine `run.sh`

**Comment by grady404** [comment]
Alright, what's the command to bring up the console?

**Comment by cooperuser** [comment]
`Command + Option + I`

**Comment by cooperuser** [comment]
Or `View > Toggle Developer Tools`

**Comment by grady404** [comment]
Uh, did I do something wrong? I just ran the `.app` file, do I have to run it using some other method?

**Comment by cooperuser** [comment]
You run the `.sh` file

**Comment by grady404** [comment]
I wonder if I ran the `chmod` command wrong somehow. When I double click it opens in Xcode. Nothing else of use shows up in the "Open With" menu

**Comment by cooperuser** [comment]
Manually open with Terminal

**Comment by grady404** [comment]
Oh ok. Looks like I need to download Electron itself

**Comment by cooperuser** [comment]
Do you not have it?

**Comment by cooperuser** [comment]
try typing `electron` in terminal

**Comment by grady404** [comment]
No, I don't have it

**Comment by cooperuser** [comment]
Oh

**Comment by grady404** [comment]
https://github.com/electron/electron/releases/tag/v1.4.3

Do I want the `mas` version?

**Comment by cooperuser** [comment]
`electron-v1.4.3-darwin-x64.zip`

**Comment by cooperuser** [comment]
Did it work?

**Comment by grady404** [comment]
Yep

**Comment by cooperuser** [comment]
Awesome
