### ISSUE TITLE
Level rating system for development builds

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#57]
Something that I thought would be helpful for playtesting... implement an interface for the player to rate the difficulty and quality (separately, each from 0 to 5) of a level immediately after completing it. The players wouldn't be able to bypass this screen. This would allow us to collect data on which levels players find the most difficult, so we can put the levels in the correct order; as well as how much they enjoyed the level, so that we can remove the levels that players don't respond as positively to. The only question is how we would actually retrieve this information. We could just tell our playtesters to email the `ratings.json` file to us after completing the game, or to make the system foolproof, we could have the game upload their ratings to a web server as they play (which would be more difficult). If you choose the second option, you should still store the ratings in a local file so that they don't need an Internet connection to play, and upload them to the server as soon as the game re-connects to the Internet.

**Comment by cooperuser** [comment]
I think this is a good idea, but should the user be able to change their rating afterwards? Like if the user gave a 5 star rating, then after submitting thought that they should have given a 4 star, should they be able to change it?

**Comment by grady404** [comment]
Replaying the level would cause the interface to be displayed again, so yeah, they could change it.

**Comment by grady404** [comment]
But finish the overhaul before you do this, obviously. After you finish the overhaul (and upload it to the repository) you should check some of the stuff in the Playtesting milestone. By the way, does the level editor work since the overhaul?

**Comment by cooperuser** [comment]
I have been experimenting with many different types of ways of rendering the game, but I can not seem to find one that will be future-proof, as in, it will work with teleporters and stuff

**Comment by grady404** [comment]
What is the "and stuff"? I think getting it to work with teleporters should be fine, every time the block teleports just start the move sequence again. If the block goes through a teleporter, the move sequence should take 800ms–400ms before entering the teleporter and 400ms after.

**Comment by grady404** [comment]
And I think we came to the conclusion that your version of the teleporter was better, but I can't remember why, can you remind me?

**Comment by cooperuser** [comment]
Consistency among block clusters

**Comment by cooperuser** [comment]
<img src="http://ghchart.rshah.org/cooper-anderson" alt="My Contributions Chart" />
Also! check this out!

**Comment by grady404** [comment]
Oh yeah, right. Hmm... we might actually want to have two types of teleporter clusters, although I don't know if this is overcomplicating things. One type would only take block clusters that are the exact same shape as the teleporter, the other would take any block cluster as long as every block within it was able to align to one of the teleporter blocks. So a 1x3 teleporter of Type A wouldn't accept a 1x2 block, but a Type B teleporter would.

**Comment by grady404** [comment]
And what is that? Are those all the dates we created issues, or something?

**Comment by cooperuser** [comment]
No, that is my contributions chart, which you can see [here](https://github.com/cooper-anderson), but I found a way to make it into an `<img>` tag and embed it anywhere!

**Comment by cooperuser** [comment]
Which means, in the free time I have where I am not working on the game, I can be working on a better notifications app!

**Comment by cooperuser** [comment]
Which reminds me, When you showed me that chart about steam games and the profit, did you consider the amount of money that is taken by Valve?

**Comment by grady404** [comment]
Yeah, I did. I heard something like 30% when you include taxes, but that's quoted from some random dude on Reddit or something, so don't take my word on that. I'm going to look it up to get the actual amount haha

**Comment by cooperuser** [comment]
Okay

**Comment by grady404** [comment]
It's around 30%, which seems like a lot. See [this](http://www.pcgamer.com/notch-on-why-minecraft-still-isnt-on-steam/) article, I found it interesting, and it makes me wonder about the option of self-publishing the game.

**Comment by cooperuser** [comment]
Interesting post, but even if there is a big chunk of the money that goes to Valve, I think the exposure is good

**Comment by grady404** [comment]
Yeah, that's the tradeoff. But it makes me wonder if there are any alternatives to Steam that would give us comparable exposure. We can look into it

**Comment by grady404** [comment]
And what do you think of that teleporter idea above? Too confusing?

**Comment by cooperuser** [comment]
The two different kinds of teleporters? I think that it isnt the craziest idea we've had

**Comment by cooperuser** [comment]
On another note though, about fancy animations. Have you heard of the game Shellshock Live? Because it has probably the fanciest 2d animations I have seen in a game. When you unlock something new it just has this cool effect, and there is pretty much different effects for each thing. Not much I can explain just by saying it though

**Comment by grady404** [comment]
I'll look up some videos of it

**Comment by cooperuser** [comment]
Okay, sound good

**Comment by grady404** [comment]
I think what you're talking about is "game feel" - every time something happens, the game should give you plenty of feedback to let you know something occurred. I don't think we should overdo it in this game as much as to ruin the minimalist feel, but some extent of this type of feedback would be much needed

**Comment by grady404** [comment]
Oh and you never answered my question, does the level editor work as of the overhaul?

**Comment by cooperuser** [comment]
No, not yet

**Comment by grady404** [comment]
Alright, I'd go ahead and work on the visual stuff first

**Comment by cooperuser** [comment]
Yeah, my thoughts exactly

**Comment by grady404** [comment]
The rating system is functional and saves the information to a JSON file for each level. Online data submission will be added later (see #84).
