### ISSUE TITLE
Reorganize the file system

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#6]
I think you should entirely change the places where all the data is stored in the game. I suggest you store the data in this hierarchy:

```
app {
  package.json
  source {
    unlocked-levels.json [TEMP]
    scripts {
      html {...}
      js {...}
      css {...}
    }
    resources {
      sprites {...}
      fonts {...}
      audio {
        sounds {...}
        music {...}
      }
    }
    default-levels {...}
    bonus-levels {...}
    themes {...}
  }
  save-data {
    preferences.json
    progress {...}
    user-levels {...}
  }
}
```

`source` contains all the scripts and resources needed to run the game, and `save-data` takes care of all user data. This way, all the user needs to do to backup their save data is backup the `save-data` folder, and they won't have to unnecessarily copy any other files.

**Comment by grady404** [comment]
Edit: I actually think you should entirely change the places where all the data is stored. Get rid of the current `assets` folder (all it contains is an unused block sprite), and store the data in this hierarchy:

`app` {
..`assets` {
....`app-files`
....`default-levels`
....`themes`
..}
..`save-data` {
....`progress`
....`custom-levels`
..}
}

`app-files` contains all the HTML, CSS, and JavaScript files to run the game (and font files), and the rest of the folders are pretty much self-evident. This way, all the user needs to do to backup their save data is, well, backup the `save-data` folder.

**Comment by cooperuser** [comment]
I think this is a good way of doing this, which one exception, the actual webpage loads off of the `index.html` in the `/app` directory.

**Comment by grady404** [comment]
That's fine, but what I would actually do is move the current `index.html` into the `/app/assets/app-files` folder and name it `startup.html`, and make the `/app/index.html` file a redirect to `/app/assets/app-files/startup.html`. That way there's no actual code in `/app/index.html` (well besides the redirect of course).

**Comment by grady404** [comment]
Once you finish all of this, make it so that if the user deletes the `/app/save-data` directory or any of its subdirectories, the game will replace them.

**Comment by cooperuser** [comment]
replace them with new blank save data?

**Comment by grady404** [comment]
Yeah, sort of... If the user deletes `/app/save-data/progress` you don't want to replace the _entire_ `/app/save-data` folder with a blank one (which would also delete their custom levels), just the `progress` subdirectory, same goes for `/app/save-data/custom-levels`. But if the user deletes `/app/save-data`, then it should replace that with a new `/app/save-data` folder containing blank `progress` and `custom-levels` subdirectories.

**Comment by grady404** [comment]
Don't worry about this yet though, just reorganize everything first.

**Comment by cooperuser** [comment]
yeah

**Comment by grady404** [comment]
And once you've reorganized it update the repo, and update it again once you did the folder-replacement thingy. Don't wait until you have both to update the repo.

**Comment by cooperuser** [comment]
Yeah, I usually try to push as much as possible because it gives me more documentation for my badges project.... shhhh

**Comment by grady404** [comment]
Oh I didn't know you were using this for your badges project

**Comment by grady404** [comment]
Why don't you have your badge yet? I got mine last year, and I made less games than you did...

**Comment by cooperuser** [comment]
I wasnt at first, but then someone said that this game was addicting, so... i just made it my project

**Comment by cooperuser** [comment]
Sorry, didnt see that last message for some reason. but the reason I didnt get a badge was because I was really bad at documenting my work. But now that I have made this project, I have gotten akin to documenting as I go, or just from past projects, so I will be getting my badge soon.

**Comment by grady404** [comment]
Ah I see. When I made my games I didn't document every tiny step in the process, I just had really detailed and informative presentations and stuff.

**Comment by cooperuser** [comment]
Oh, I guess that is a way of doing it

**Comment by grady404** [comment]
You going to do this?

**Comment by cooperuser** [comment]
This will be built in to the re design

**Comment by grady404** [comment]
I would do this first, it'll put you on good footing for the redesign, and the redesign is multiple stages, it's not one singular thing. I think this should go first

**Comment by cooperuser** [comment]
But why do it twice?

**Comment by grady404** [comment]
You won't... this is just reorganizing where files are stored. It has nothing to do with the actual _format_ of the files (i.e. the level files)

**Comment by grady404** [comment]
This should be your top priority at the moment. You don't need to wait for the overhaul to do this

**Comment by grady404** [comment]
Ok, I think you should temporarily store `progress.json` in `/app/save-data/`, we will replace that file with a new level unlock system later.

**Comment by grady404** [comment]
By the way, the rule is, if the player can modify it it goes in `/app/save-data/`, if they can't it goes in `/app/assets/`

**Comment by cooperuser** [comment]
```
app/
    assets/
        app-files/
            <index.html etc etc>
        default-levels/
            <levels>
        themes/
            <themes>
    save-data/
        progress.json
        custom-levels/
            <levels>
```

**Comment by cooperuser** [comment]
Are themes created? or are they selected

**Comment by grady404** [comment]
Selected, if users can create them that takes the value out of them

**Comment by cooperuser** [comment]
It does?

**Comment by grady404** [comment]
Yeah, because they're unlockable

**Comment by cooperuser** [comment]
oh! one requirement about this structure... the `package.json` **must** be in `app/`. so `app/package.json`

**Comment by cooperuser** [comment]
Oh

**Comment by grady404** [comment]
Oh ok that's fine, but why is that? I thought that was something you created to store the version number and stuff.

**Comment by cooperuser** [comment]
Node.js

**Comment by cooperuser** [comment]
and npm

**Comment by grady404** [comment]
Alright. Would it be easy to access `/app/package.json` from `/app/assets/app-files/`?

**Comment by grady404** [comment]
`../../package.json`?

**Comment by cooperuser** [comment]
no, I do not need to access it, `Node.js` does

**Comment by cooperuser** [comment]
and that is done automatically

**Comment by grady404** [comment]
But you store the version number in there.

**Comment by cooperuser** [comment]
yes

**Comment by cooperuser** [comment]
well, I do access it, but thats besides the point

**Comment by grady404** [comment]
so doesn't `menu.html` need to access it? in that case it's easy right?

**Comment by cooperuser** [comment]
in order for `Electron` to run the game, it must find `package.json` in the root directory

**Comment by cooperuser** [comment]
if not, there are issues with the File System API

**Comment by cooperuser** [comment]
and it cant run...

**Comment by grady404** [comment]
I get that, but it's easy for _your_ files to access it even if they're in a "deeper" directory, right?

**Comment by cooperuser** [comment]
oh

**Comment by cooperuser** [comment]
I completely misread what you were saying

**Comment by cooperuser** [comment]
I thought that you meant that I could make it so electron looks in `../../package.json`

**Comment by grady404** [comment]
Oh, haha, was it ambiguous?

**Comment by cooperuser** [comment]
half you, half me

**Comment by grady404** [comment]
Anyway... it's easy right

**Comment by grady404** [comment]
Ok see the new file structure

**Comment by cooperuser** [comment]
Wheres the new file structure?

**Comment by grady404** [comment]
Btw, move the current `/app/index.html` to `/app/assets/app-files/startup.html` and make the new `/app/index.html` a redirect to that.

And the new file structure is at the top

**Comment by cooperuser** [comment]
btw you do know that you can use three 

```
`
```

marks to do this right?

**Comment by grady404** [comment]
No, but I like how I did it, only the directory names are in code quotes

**Comment by cooperuser** [comment]
?

**Comment by cooperuser** [comment]
Also, in pretty much every game that uses an `assets` folder, it is used for sprites and other resources only. Shouldnt we keep code in a separate directory?

**Comment by cooperuser** [comment]
like a python `script` convention, or other times there is `lib`

**Comment by cooperuser** [comment]
Also, according to versioning convention, making this change will put this game into `v1.0.0`

**Comment by cooperuser** [comment]
I know! we can make it `v1.0.0-alpha`

**Comment by cooperuser** [comment]
and then once I finish the overhaul #39, it can be `v1.0.0`

**Comment by cooperuser** [comment]
or should this just be `v0.2.0`, cause that would make sense too

**Comment by cooperuser** [comment]
Oh! and also... we kinda need the `node_modules/` directory directly inside `app/`

**Comment by grady404** [comment]
I like the idea of having one directory for immutable files and one for mutable files. You're right that `assets` isn't the best name, any idea for a better name?

**Comment by grady404** [comment]
And no Cooper, making that change won't put the game into `v1.0.0`

`4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.`

**Comment by cooperuser** [comment]
`lib`, `Contents` (like Mac)

**Comment by cooperuser** [comment]
> 1. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by cooperuser** [comment]
if you do `> <stuff>`

**Comment by cooperuser** [comment]
Once I finish the overhaul, that will be `v1.0.0`

**Comment by grady404** [comment]
What's `node-modules`? I don't see that

**Comment by cooperuser** [comment]
oh it is under the `reworked all` branch

**Comment by cooperuser** [comment]
Its used for imports

**Comment by cooperuser** [comment]
I'm gonna see if there is a work-around though

**Comment by grady404** [comment]
It's something required by Electron? Then why don't you have it?

**Comment by cooperuser** [comment]
No, it is part of node, you know how in python you can do

``` python
import Vectors
```

where Vectors is actually `Vectors.py` in the same directory?

**Comment by cooperuser** [comment]
Fixed

**Comment by grady404** [comment]
Oh so you don't need it in the `/app/` directory anymore?

**Comment by grady404** [comment]
Is `resources` a better name for `assets`? Or does that still imply art-focused stuff (graphics, textures, models, audio, etc.)

**Comment by cooperuser** [comment]
I had thought of that too, I'm still not sure...

**Comment by cooperuser** [comment]
oh!!!

**Comment by cooperuser** [comment]
`src`

**Comment by grady404** [comment]
"Explicit is better than implicit."
-The Zen of Python

I would try to avoid abbreviations and make it more verbose. So `source`?

**Comment by grady404** [comment]
Wait, haha, I'm an idiot, why don't you call _that_ directory `app-files`, and rename the current `app-files` to `scripts` (see the top of the page if you're confused)

**Comment by cooperuser** [comment]
<img width="477" alt="screen shot 2016-09-10 at 9 53 10 pm" src="https://cloud.githubusercontent.com/assets/21961037/18415271/037c2d8e-77a1-11e6-861c-d0a31d206c3d.png">

**Comment by grady404** [comment]
Yeah, I don't like `src`, I want these directories to be as easy to navigate and understand as possible

**Comment by cooperuser** [comment]
that example was some minecraft modding, and that is what Mojang used

**Comment by grady404** [comment]
And Mojang used _Java_.

**Comment by cooperuser** [comment]
good point.... -.-

**Comment by cooperuser** [comment]
so should it be

```
app/
├──source/
│  ├──js/
│  │  ├──main.js
│  │  ├──play.js
│  │  └──editor.js
│  ├──css/
│  │  └──stylesheet.css
│  └──index.html
├──resources/
│  ├──assets/
│  │  └──block.png
│  └──sounds/
│     └──blockSlide.wav
├──user-data/
│  ├──user-levels/
│  └──progress.json
└──package.json
```

**Comment by grady404** [comment]
No. Let me fix that

**Comment by cooperuser** [comment]
resources should be in source?

**Comment by grady404** [comment]
I'm editing the hierarchy up at the top. I'll tell you when I'm finished

**Comment by cooperuser** [comment]
no problem

**Comment by grady404** [comment]
Wait. How did you get `index.html` into `/app/source/`?

**Comment by cooperuser** [comment]
I found a way

**Comment by grady404** [comment]
And where will all the other `.html` files go?

**Comment by cooperuser** [comment]
either directly in `/source/` or they can go in a `/html/` directory, but I prefer in `/source/`

**Comment by cooperuser** [comment]
Oh! and dont forget about `/default-levels/`

**Comment by grady404** [comment]
Honestly, I don't think so, I think it's a bad idea for a directory with subdirectories to be cluttered with files and you'd best avoid that if you can help it

**Comment by cooperuser** [comment]
But all webpages do that, its convention

**Comment by cooperuser** [comment]
you have subdirs for `css` and `js` but not for `html`

**Comment by grady404** [comment]
But it's a bad convention...

"Owning slaves used to be convention"
-Overused logical fallacy example

**Comment by grady404** [comment]
I think it's because web devs get lazy and don't want to do `../` to access css and js files

**Comment by cooperuser** [comment]
oh

**Comment by grady404** [comment]
But I would tend toward ease of navigation for users than ease of access for developers

**Comment by cooperuser** [comment]
Ease of navigation?

**Comment by grady404** [comment]
Yeah, for users navigating the filesystem

**Comment by cooperuser** [comment]
Users would not need to be looking in these directories though

**Comment by cooperuser** [comment]
Hang on, I'm gonna go check some electron examples

**Comment by cooperuser** [comment]
see what they did

**Comment by grady404** [comment]
In alpha and beta up until release, I think they will

**Comment by grady404** [comment]
We won't encrypt that stuff until we fully release the game and there are online leaderboards

**Comment by cooperuser** [comment]
https://github.com/minbrowser/min

**Comment by cooperuser** [comment]
https://github.com/zz85/space-radar

**Comment by grady404** [comment]
Do whatever you want... I'm just saying that I think we should be consistent and not clutter up any of the directories that have subdirectories

**Comment by cooperuser** [comment]
Okay, we can always change later if need be

**Comment by grady404** [comment]
Sure

**Comment by grady404** [comment]
Just go ahead and get this finished... I think we (you) had better move on to more important stuff

**Comment by cooperuser** [comment]
yeah, but one more thing. I am going to be storing all of the `Block`subclasses in one file, all of the `Plate`subclasses in one file, and all of the `Tiles`subclasses in one file. They will all be in javascript files, but do you think they should just be in `/js/` or should be they be in `/js/objects/` or something

**Comment by grady404** [comment]
hhmmmmmmm I just had an idea

**Comment by grady404** [comment]
Oh and huh idk

**Comment by grady404** [comment]
I would do that, yeah

**Comment by cooperuser** [comment]
okay

**Comment by cooperuser** [comment]
and whats your idea?

**Comment by cooperuser** [comment]
Oh and do you think that subclasses should be in their own js file? or all in one. If they are in multiple, then it would make modding easier

**Comment by grady404** [comment]
Right. So I just had a moment of "oh, duh" and realized that online leaderboards wouldn't work at all for this game (because the top 10, 100, 1000, whatever would all have the same score, and on that note I don't think Time is a good thing to put on leaderboards since it involves skill rather than strategy). So, that kind of stuff would probably only be with people on your Steam (or GameCenter, or whatever) friends list so that you can directly compete with your friends for best Moves and Distance scores. In that case, it really doesn't matter if someone wants to go screw with their game files to give themselves some crazy score, since they'd only be messing with their friends, not screwing over everyone in the entire world who plays the game.

Now there is another reason I wanted to encrypt level files. First let me get back to the "moves" attribute in the JSON file of each level. Unless I can ridiculously improve the efficiency of my level verification algorithm, there are going to be certain levels that we just aren't going to be able to find the best possible Moves/Distance scores for. So I think instead of labeling it as a "perfect score", we should call it the "developer score", which would challenge players to attempt to beat our score on some levels, if it's possible. If a player beat one of our scores, it would send that score to a server to notify us, and we would try to beat their score (but if we couldn't we'd just look at their solution). If we didn't encrypt level files, someone would just mess with the level until they could get a Moves/Distance score of 1 or 0, then we'd get notified, and this would probably happen all the time. But in another "oh, duh" moment, I realized that we could just have the server verify the solution to make sure it is correct.

So there you go, I don't think we should encrypt level files. I think we should let the players who want to mess with them mess with them.

**Comment by grady404** [comment]
And yeah, I would put each of the subclasses in different files, but just put all objects, regardless of hierarchy, in the same folder for now.

**Comment by cooperuser** [comment]
Yeah all of those things you mentioned have crossed my mind some time before, especially the online leaderboard conundrum, but I had never considered having the server check the solution, thats a great idea

**Comment by cooperuser** [comment]
As for the hierarchy, I was planning on having all `Block` subclasses be in a `/js/Block/` directory

**Comment by grady404** [comment]
oh waaaaaait... I just had my third and final (hopefully) "oh, duh" moment

**Comment by grady404** [comment]
the biggest one yet

**Comment by cooperuser** [comment]
oh?

**Comment by grady404** [comment]
if the server can check the solution when they try to beat the dev score, the server can _also_ check the solution if they attempt to upload a score to the leaderboard

**Comment by grady404** [comment]
Oh, actually, I like the `/js/Block/` idea, so do that then

**Comment by grady404** [comment]
As long as what you're doing over there doesn't involve any code rewriting, just file reorganization

**Comment by cooperuser** [comment]
okay, and can you elaborate on your third and hopefully not final (because these idea are great) oh duh moments please? it was a bit ambiguous

**Comment by grady404** [comment]
My thought process:
- Well, we can't create a leaderboard because people can hack it. Oh well, we don't need one.
- But what we _can_ do is have a server check their solution if they attempt to beat the dev score.
- Oh shit, we can use the solution checker for the leaderboard problem too. I'm an idiot.

**Comment by cooperuser** [comment]
We just need to keep a log of their moves

**Comment by cooperuser** [comment]
have the server run this simulation, and if it wins, then say so

**Comment by grady404** [comment]
My thought process was akin to this:
- Oh crap, I can't open this cookie jar, it's stuck shut. Guess I can't have a cookie.
- But I can open this jar of brownies using a pocket knife, so I can at least have that.
- Oh shit, of course, I can use the pocket knife to open the cookie jar also.

**Comment by cooperuser** [comment]
hahahahahahahahha

**Comment by grady404** [comment]
And yeah, a log of their moves obviously

**Comment by cooperuser** [comment]
that analogy.... was the most beautiful analogy ever

**Comment by grady404** [comment]
Yes. Isn't it perfect
- [ ] yes

**Comment by cooperuser** [comment]
I kind of want to post your analogy on the `README.md`.... beacuse of how gold it was

**Comment by grady404** [comment]
Hahaha where on there would you put it?

**Comment by cooperuser** [comment]
Not sure, I was planning on adding a `/doc/` directory for more in-depth teaching, maybe hidden in there somewhere?

**Comment by grady404** [comment]
Haha sure

**Comment by grady404** [comment]
Put it with the original statement obviously

**Comment by cooperuser** [comment]
of course

**Comment by cooperuser** [comment]
save it somewhere, ill add it to it later

**Comment by cooperuser** [comment]
well that comment didnt make much sense, i edited it tho

**Comment by cooperuser** [comment]
Oh! should the `/font/` directory be in `/resources/`? i think so

**Comment by grady404** [comment]
You mean `/assets/`? (I think I like resources better than assets though, I'll go ahead and change that)

**Comment by grady404** [comment]
And the answer is yes, I think so too

**Comment by cooperuser** [comment]
I have `/resources/` and `/resources/assets/` I will be using `/assets/` for images and sprites

**Comment by grady404** [comment]
Make it `fonts`, not `font`

**Comment by cooperuser** [comment]
I was planning on that too

**Comment by grady404** [comment]
Use `sprites` for sprites...

**Comment by grady404** [comment]
"Explicit is better than implicit"

**Comment by grady404** [comment]
Besides, assets usually applies to _all_ non-code files used to run a game

**Comment by cooperuser** [comment]
oh?

**Comment by cooperuser** [comment]
because I was planning on having `resources/assets/blocks/`

**Comment by grady404** [comment]
`/resources/sprites/blocks/`

**Comment by grady404** [comment]
Unless you're putting other stuff in there besides sprites

**Comment by cooperuser** [comment]
hmm...

**Comment by grady404** [comment]
And why? Are you eventually going to add textures to the blocks? I really don't like that idea personally...

**Comment by cooperuser** [comment]
i was gonna have `/resources/assets/`and (`/resources/sounds/` or `/resources/sounds/`)

**Comment by grady404** [comment]
"(`/resources/sounds/` or `/resources/sounds/`)"
aren't those the exact same thing...

**Comment by cooperuser** [comment]
Well, I dont want to use `class="btn btn-info diabled"` forever

**Comment by grady404** [comment]
And no, do `sprites`, `sounds`, `music`, and `fonts`

**Comment by cooperuser** [comment]
oh i meant one to be `audio`

**Comment by grady404** [comment]
And no, if you use buttons you can change the color (themes, remember?). With sprites you can't.

**Comment by cooperuser** [comment]
oh.....

**Comment by grady404** [comment]
Oh yeah I would do `/resources/audio/sounds/` and `/resources/audio/music/` to keep them in the same category but also separate

**Comment by cooperuser** [comment]
I was also planning on using connected textures. here was some testing I was doing earlier:
<img width="1860" alt="screen shot 2016-09-10 at 8 57 06 pm" src="https://cloud.githubusercontent.com/assets/21961037/18415530/30a380ba-77aa-11e6-9253-0b6eff82d64e.png">

**Comment by grady404** [comment]
Oh whoa, that does look really nice actually. But would you be able to change the color?

**Comment by cooperuser** [comment]
Yes

**Comment by grady404** [comment]
Ok, cool, that works

**Comment by cooperuser** [comment]
Also for the `hollow block`, a disabled anchor tag doesnt really work

**Comment by grady404** [comment]
Ok, see new directory at the top

**Comment by grady404** [comment]
And wait, is it possible to change the color of sprites?

**Comment by cooperuser** [comment]
yes

**Comment by grady404** [comment]
Oh ok, that clears things up

**Comment by cooperuser** [comment]
because it is white, I can do color multiply

**Comment by grady404** [comment]
True

**Comment by grady404** [comment]
Well definitely be sure to keep every color editable

**Comment by cooperuser** [comment]
Of course

**Comment by grady404** [comment]
How far have you gotten with the reorganization btw?

**Comment by cooperuser** [comment]
at the top, you called it `app-files`? didnt we decide on `source`?

**Comment by cooperuser** [comment]
<img width="410" alt="screen shot 2016-09-10 at 11 04 29 pm" src="https://cloud.githubusercontent.com/assets/21961037/18415550/f4469886-77aa-11e6-8b02-9708ec136f02.png">

**Comment by grady404** [comment]
No, that's not verbose enough, it sounds like that only contains code

**Comment by grady404** [comment]
Maybe not actually. Guess I do like that after thinking about it

**Comment by grady404** [comment]
I'll change it

**Comment by cooperuser** [comment]
I just have `/resources/`, `/source/` and `package.json` in the same directory

**Comment by grady404** [comment]
What do you like better?

`default-levels` and `custom-levels`
`default-levels` and `user-levels`

**Comment by grady404** [comment]
Nononono, put resources inside source

**Comment by grady404** [comment]
Are you even looking at what I have at the top of the page?

**Comment by cooperuser** [comment]
put resources inside source?

**Comment by cooperuser** [comment]
- [ ] `default-levels` and `custom-levels`
- [x] `default-levels` and `user-levels`

**Comment by grady404** [comment]
```
app {
  package.json
  source {
    unlocked-levels.json [TEMP]
    scripts {
      html {...}
      js {...}
      css {...}
    }
    resources {
      sprites {...}
      fonts {...}
      audio {
        sounds {...}
        music {...}
      }
    }
    default-levels {...}
    bonus-levels {...}
    themes {...}
  }
  save-data {
    preferences.json
    progress {...}
    user-levels {...}
  }
}
```

**Comment by grady404** [comment]
Ok I'll make it user-levels then

**Comment by cooperuser** [comment]
I have looked at it, i just think that they should be separate

By the way, you know you can edit someone else's comment right? -Grady

**Comment by grady404** [comment]
Here's why I don't

**Comment by grady404** [comment]
The `/app/` directory contains two folders: `source` and `save-data`. _One is mutable, the other is immutable. One changes as the user plays the game, the other only changes when the game is updated._

**Comment by cooperuser** [comment]
but then `/resources/` would be in the same directory as `/css/`, `/js/` and all of the `html` files

**Comment by cooperuser** [comment]
oh `scripts`

**Comment by grady404** [comment]
Nope, it wouldn't, check the hierarchy

**Comment by grady404** [comment]
Yes exactly

**Comment by cooperuser** [comment]
this is gonna cause a lot of `../../../../`s

**Comment by grady404** [comment]
yep

**Comment by grady404** [comment]
wait a sec... idk if this is taking the whole filesystem thing too far... but what if you had a JSON file inside of `/app/` that you referred to to figure out where everything was? That way you could change the location of directories much more easily...

**Comment by cooperuser** [comment]
I had already considered that

**Comment by grady404** [comment]
- [ ] yes or
- [ ] no?

**Comment by cooperuser** [comment]
yes or no to 
- [ ] "wait a sec..."
- [ ] using `script`

**Comment by grady404** [comment]
what?

**Comment by cooperuser** [comment]
I was confused as to what you were asking "yes or no" to

**Comment by grady404** [comment]
Yes or no to having a JSON file that keeps track of the locations of all folders
- [ ] yes
- [ ] no
- [x] maybe

**Comment by cooperuser** [comment]
that seems a bit hacky, and prone to user modding

**Comment by cooperuser** [comment]
but then, we could just encrypt it

**Comment by grady404** [comment]
It's fine if users mod it

**Comment by grady404** [comment]
And I guess it's hacky... but not really... what makes you say it's hacky

**Comment by cooperuser** [comment]
seems a bit unprofessional

**Comment by grady404** [comment]
Sure, I guess. Don't worry about it yet, just reorganize all the files first

**Comment by cooperuser** [comment]
we are having problems.... issues loading running game at startup

**Comment by grady404** [comment]
did you "finish" reorganizing everything?

**Comment by cooperuser** [comment]
no, but i was testing running the game because if that didnt work, then all would have been for nothing

**Comment by cooperuser** [comment]
Im just trying to get the game to start again

**Comment by grady404** [comment]
is it logging errors?

**Comment by cooperuser** [comment]
it was, now its not even doing that

**Comment by grady404** [comment]
huh, that's really strange. I guess try moving index.html back out to the root and see if that has anything to do with it

**Comment by cooperuser** [comment]
ah, fixed

**Comment by grady404** [comment]
cool

**Comment by grady404** [comment]
what have you done so far?

**Comment by cooperuser** [comment]
<img width="418" alt="screen shot 2016-09-10 at 11 38 43 pm" src="https://cloud.githubusercontent.com/assets/21961037/18415683/bd15bba8-77af-11e6-9e87-03c517b0d2af.png">

**Comment by grady404** [comment]
Ooh nice, everything works?

**Comment by cooperuser** [comment]
not everything yet

**Comment by cooperuser** [comment]
btw should it be called `user-data` or `save-data`

**Comment by grady404** [comment]
I think `save-data` is more verbose, so it will be more clear for players trying to back up their save file

**Comment by grady404** [comment]
And by "everything" I meant everything you had done so far

**Comment by cooperuser** [comment]
yeah

**Comment by grady404** [comment]
I assume `data` is just a remnant from the past version right?

**Comment by cooperuser** [comment]
yup

**Comment by grady404** [comment]
Thought so

**Comment by cooperuser** [comment]
should it be called `default-levels` or just `levels`

**Comment by grady404** [comment]
`default-levels`

**Comment by cooperuser** [comment]
okay

**Comment by grady404** [comment]
More explicit that way

**Comment by cooperuser** [comment]
Level select and default levels working again

**Comment by grady404** [comment]
sounds good

**Comment by cooperuser** [comment]
ahh! okay! done!

**Comment by grady404** [comment]
Everything?

**Comment by cooperuser** [comment]
pretty much

**Comment by grady404** [comment]
Nice going, that was fast

**Comment by grady404** [comment]
Btw... where did all the other user levels go in the repo? There are only a few left...

**Comment by grady404** [comment]
And you can go ahead and update the repo when you're ready, I'll follow with some new/updated levels

**Comment by cooperuser** [comment]
A lot of them were junk, so i be-ridded of them

**Comment by grady404** [comment]
Alright, gotcha, I'll keep them on my local drive but I won't re-upload them, in fact I might just remove all user levels in the repo

**Comment by cooperuser** [comment]
you can remove the ones from your computer that arent on the repo, unless they are yours

**Comment by grady404** [comment]
The only people besides us who had levels in there were Antony and E'danel

**Comment by grady404** [comment]
That's only two levels, I might as well keep them

**Comment by grady404** [comment]
Yeahhh 0.2.0

**Comment by grady404** [comment]
After you test everything to make sure it works, can you merge the branches so that I can add the levels?

**Comment by cooperuser** [comment]
I am trying, there are some issues

**Comment by grady404** [comment]
Alright, tell me when you have them worked out. The levels are all set to be added

**Comment by grady404** [comment]
Are the "issues" GitHub conflicts or problems with the code?

**Comment by cooperuser** [comment]
GitHub, but i think its good now

**Comment by grady404** [comment]
Ah yeah, looks like it's working great, one thing though - could you clear the `user-levels` folder? I have them all on my local drive, and people downloading the game don't need them. (`v0.2.2`)

**Comment by cooperuser** [comment]
sure

**Comment by cooperuser** [comment]
I could just make it that it doesnt upload them, and just keeps them on my local disk

**Comment by grady404** [comment]
Sure, you can back them up to your drive, I have them on mine. Just remove them from the repo

**Comment by grady404** [comment]
I actually really like the way you've organized the files, I like how `resources` and `scripts` are separate.

**Comment by grady404** [comment]
One thing though - where is temp.json currently stored?

**Comment by grady404** [comment]
Oh I see, it's in `user-levels`

**Comment by cooperuser** [comment]
yes, and i made it so it gets deleted upon level completion... although i just realized it should also be deleted upon quit too

**Comment by grady404** [comment]
Okay, weird request, do you think you could move `progress.json` to `source/resources` instead of `save-data`, and rename it to `unlocked-levels.json`? Right now it's not actually a progress file, all it basically does is determine what colors the icons on the level select screen are. You can move it back when you implement actual progress tracking.

**Comment by cooperuser** [comment]
why do that though?

**Comment by grady404** [comment]
Actually, can you move it to `source/resources/default-levels/unlocked.json`? I want it in the same directory as the levels, because every time I add levels I update that file, and it's a lot more convenient for all the files I upload to be in the same folder.

And regarding `temp.json`, see #7

**Comment by grady404** [comment]
I know that seems weird, but it's not actually a progress file yet since it doesn't have full functionality

**Comment by cooperuser** [comment]
Now that, will be done in the overhaul

**Comment by grady404** [comment]
Just do this as a temp fix for now. You'll implement the _actual_ progress tracking in the overhaul

**Comment by grady404** [comment]
I want to upload my levels, but only want it to be one commit, and don't want to deal with weird directory paths

**Comment by grady404** [comment]
`progress.json` itself was a temporary fix, so just move it, as another temporary fix.

**Comment by cooperuser** [comment]
why though? that makes no sense

**Comment by grady404** [comment]
Yes it does. Whenever I add a new level, I have to add it to that file so it displays as blue. And when I add new levels to the repo, I want all the new/updated files to be in the same folder.

**Comment by grady404** [comment]
Move it from `save-data/progress.json` to `source/resources/default-levels/unlocked.json`

**Comment by cooperuser** [comment]
I could just get to work on the overhaul, and fix all these problems... making me do these now is just making me have to redo them later

**Comment by grady404** [comment]
It'll literally take all of three minutes

**Comment by grady404** [comment]
The overhaul will take a couple more days, probably...

**Comment by cooperuser** [comment]
No. i could probably finish it tonight

**Comment by grady404** [comment]
Really? But I want to add my levels regardless, so I don't have this useless folder sitting on my desktop. Besides, we're going to _completely_ redo the progress system, so this file is going to become deprecated anyway - see #28

**Comment by grady404** [comment]
It's not like you'll move it and then need to move it back later. You'll move it and then delete it with the overhaul

**Comment by grady404** [comment]
you literally have to change _one_ line of code...

**Comment by cooperuser** [comment]
and move the file and rebase the repo, and resync webstorm

**Comment by grady404** [comment]
Versus sending five comments trying to protest me?

**Comment by cooperuser** [comment]
I just want to leave it until I implement the final thing

**Comment by grady404** [comment]
Eh, what am I doing, I can probably find that line of code myself

**Comment by cooperuser** [comment]
`levelselect.html line #65`

**Comment by grady404** [comment]
Ok don't worry about it, I already got it, it works

**Comment by grady404** [comment]
I'm going to commit it directly to master, just as a temp fix

**Comment by cooperuser** [comment]
There is literally no reason to do that

**Comment by cooperuser** [comment]
so you dont have to go to a different file to make levels appear a different color

**Comment by grady404** [comment]
Well there is for me, for adding levels... you can delete it afterward anyway

**Comment by grady404** [comment]
Oh I see, you're adding it to the level JSON?

**Comment by cooperuser** [comment]
what?

**Comment by grady404** [comment]
You're going to add the color the level is displayed as to its `.json` file?

**Comment by cooperuser** [comment]
no the color the level appears in the level select

**Comment by cooperuser** [comment]
if its unlocked or not

**Comment by grady404** [comment]
I think the display color should be in the JSON

**Comment by cooperuser** [comment]
in for example, `level3.json`?

**Comment by grady404** [comment]
Yes, you would have an attribute like `level-select-color`

**Comment by cooperuser** [comment]
then you would have to modify the level JSON when you beat it.

**Comment by cooperuser** [comment]
uhh... Grady where has the `/save-data/` directory gone?

**Comment by grady404** [comment]
Uh, this must be a thing with Git but it appears that a directory must have a file within it to stay in place... and that directory is currently empty... what do I do? I shoved a temp file in there for the time being...

**Comment by cooperuser** [comment]
Its fine, I am going to have it that when loading the game, if it does not see a `/save-data/` it creates one with an empty `/user-levels/` folder and `progress.json`

**Comment by grady404** [comment]
Ok Cooper, I already called for a complete overhaul of the way progress works - see #28 

The display color wouldn't have anything to do with the user's progress, here's how it would work: if a level is uncompleted, it would show up in its respective color, and if it is completed it would either be a darker version of the same color or have a certain border around it (such as green). The display color would make it so that the Zelda levels would display as green instead of blue, so you could distinguish them.

**Comment by grady404** [comment]
I already got rid of progress.json and moved it like I said, and as I said above see #28 - we're going to completely redo the progress system

**Comment by cooperuser** [comment]
How often will this level color be used? is it going to look like a crazy mess of different bootstrap button colors?

**Comment by grady404** [comment]
No, it'll only be used for different categories of levels, or levels in different sections

**Comment by grady404** [comment]
Really, it's almost more of a temp thing until you implement the Zelda levels as secret bonus levels (I have a really cool idea for how you could do that).

**Comment by grady404** [comment]
I'll make a new issue for the Zelda thing and explain it

**Comment by cooperuser** [comment]
Why not use it as a `flag`? we already have a `flag` variable being used in the new JSON format

**Comment by grady404** [comment]
Sure, true

**Comment by grady404** [comment]
Crap dude... you can _open_ `temp.json` in the editor! Also, if you complete a level in the editor, the game freezes. I'd just do this -> #7
