### ISSUE TITLE
Add creator scores to level completion message

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#65]
Issue #41 is a prerequisite to this feature.

Here is what the new level completion message should look like. The non-bold text represents the developer/creator score, and the bold text obviously displays the score the player just achieved.
## Level Complete!

**Moves: 8** / 6
**Distance: 23** / 17

If one of the creator scores was unspecified, the message simply wouldn't display it. For example, if there was no creator score set for Distance:
## Level Complete!

**Moves: 8** / 6
**Distance: 23**

As an alternative to this style, you could try replacing the bold text with regular text and change the developer score text to a darker color, such as a shade of gray. I'll leave it to your judgement to decide which one looks nicer.

As something to think about later down the road, you might also consider changing the color of (or highlighting in some other way) either of the player's scores that matched or beat the creator scores. You don't need to worry about implementing this now, but I would suggest that the score changes to blue if it matches the creator's score, and if it surpasses the creator's score, it would turn green and a "Challenge Creator" or similar button would appear next to it.

> Just for the sake of completion, here are a couple of options I had previously brainstormed for the level completion dialog box. Don't use these, though.
> ## Level Complete!
> 
> **Moves: 8**
> **Distance: 23**
> ## Level Complete!
> 
> **Congratulations!**
> 
> **Moves: 8**
> **Distance: 23**

**Comment by grady404** [comment]
I think you should add this next, it should be very easy to implement at this point.

**Comment by grady404** [comment]
You forgot the dev score. The animation is a great touch though. I also think the Congratulations text should go, but I can take that out.

**Comment by grady404** [comment]
Oh and how about a tiny pause before the scores animate?

**Comment by cooperuser** [comment]
There is, but I can increase it

**Comment by grady404** [comment]
Make it about a third to a half of a second longer

**Comment by cooperuser** [comment]
There is currently a 400ms pause

**Comment by grady404** [comment]
I think that because there's also a 400ms pause for bringing up the dialog itself, the animation happens right after the dialog appears, so just try adding another 400ms

**Comment by grady404** [comment]
And I'll let you take out the Congratulations text since you're already making changes

**Comment by cooperuser** [comment]
I am, and also the delay was 800ms which means 400ms is happening during the animation

**Comment by cooperuser** [comment]
But I fixed it now

**Comment by grady404** [comment]
Added in 0.3.37 and 0.3.39
