### ISSUE TITLE
Remove Help modals

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#68]
Remove the button in the toolbar to view the `Help` modal. This should be easy in Play mode, since the game is built to teach the player how to play without explicitly telling them. But in the Editor mode this might be a bit more difficult, since it isn't explicitly obvious that you're supposed to right click to delete objects. My suggestion would be to implement an alternate way to delete objects one at a time (without clearing the entire tile), such as replacing the button that clears the entire tile with an "eraser" tool that only deletes the topmost object, just like the right click functionality currently does. Then once you implement hotkey functionality for the number keys (including 0), the right click functionality can be left for the power users, and won't need to be explicitly stated.

**Comment by cooperuser** [comment]
The help modal will not be included in the overhaul. In the current level editor there already is hotkey functionality for the number keys, and that will also be included in the overhaul. As for the eraser tool, I'll be considering this and other options.

**Comment by grady404** [comment]
Oh pfft, how did I not realize that was there? Guess that slipped by me. As soon as you implement the eraser tool you should be able to safely take out both help modals entirely.

**Comment by grady404** [comment]
Another possibility, you know how you had the idea of giving a little help tidbit every time you hovered over one of the objects in the editor hotbar? For the eraser tool, you could state it there that you can also right click to delete objects.

**Comment by cooperuser** [comment]
Yeah, I could of sworn I showed you the numbers to select different objects, but yeah I agree that there should not be any help modals.

**Comment by cooperuser** [comment]
Yeah, I was also thinking of that on the tooltip.
