### ISSUE TITLE
New level select sidebars

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#70]
Although I don't know what layout we would use, the new sidebars on the level select should include:
- Level number
- Name of the level
- List of level contributors
- Creator score (moves) - displays your score alongside it
- Creator score (distance) - displays your score alongside it
- Friend leaderboard (moves) - includes your score
- Friend leaderboard (distance) - includes your score

**Comment by grady404** [comment]
**blockboy12345: 9** / 10
**grady404: 10** / 10
**bobbydude444: 12** / 10

**Comment by cooperuser** [comment]
Is this what we have decided the sidebar to look like? Any changes?

**Comment by grady404** [comment]
Uh, I didn't know we had anything finalized... but I would focus on implementing `showMoveButtonsOnLoad` first, for playtesting (just remember that the game shouldn't throw an error if the `flags` variable doesn't exist)

**Comment by cooperuser** [comment]
Okay

**Comment by grady404** [comment]
And of course, for levels with that flag the buttons shouldn't go away until the user _clicks_ one of them, rather than disappearing as soon as the user hovers over the box

**Comment by cooperuser** [comment]
Actually, I have been watching some people play the first level, and they see the buttons but do not know what they are, they hover over them and nothing happens and they do not click, but then they move off of it and it disappears and they go "Oh, I see" and move back on and click a button.

**Comment by grady404** [comment]
If that's the case, I actually have the feeling that we won't want to show the move buttons at all, because I think that for the most part players will have the natural instinct to try hovering over one of the boxes (and then they will see the buttons appear, and know that they are significant). We'll have to experiment with all three different possibilities, so for now I suggest you make two flags: `showMoveButtonsUntilClick` and `showMoveButtonsUntilHover` (and I would say that the former will override the latter). When we finalize which version of the flag we will be using, we can delete the other one.

**Comment by cooperuser** [comment]
Okay

**Comment by grady404** [comment]
By the way, are you happy with the current code for the level select screen, or do you plan to rewrite it?

**Comment by cooperuser** [comment]
I did plan to rewrite it, but now that you fixed the but I don't think I will need to.

**Comment by cooperuser** [comment]
I re-added the flag by the way

**Comment by grady404** [comment]
Alright, although you might consider moving the JS code itself to a separate `levelselect.js` file if that keeps it in line with the rest of the game's code. If you do that it shouldn't interfere with the structure of the code, so it doesn't warrant a rewrite.

**Comment by grady404** [comment]
What flag?

**Comment by cooperuser** [comment]
`showMoveButtonsOnLoad`

**Comment by grady404** [comment]
And that shows it until hover? So the `showMoveButtonsOnLoadUntilClicked` will be a separate flag?

**Comment by cooperuser** [comment]
Yes, but I am still thinking of how to implement that one. Because it goes against how the selector currently works

**Comment by cooperuser** [comment]
Ah, I know

**Comment by cooperuser** [comment]
Done

**Comment by grady404** [comment]
Minor thing, if you include both `showMoveButtonsUntilClick` and `showMoveButtonsUntilHover` in the `flags` section, a very strange bug occurs. It's not a huge deal, but I suggest you make the system foolproof

**Comment by cooperuser** [comment]
Ah, okay. I will post a new issue explaining this and fix it.

**Comment by cooperuser** [comment]
Fixed

**Comment by grady404** [comment]
A new level info sidebar was implemented in `0.3.28`. See #84 regarding leaderboards.
