### ISSUE TITLE
Minor overhaul issues

### ISSUE THREAD

**Issue by grady404** [cooper-anderson/Blockade#73]
Here are a few things you should address:
- [x] Implement the overhaul into the main game, so that the level select page loads the overhauled version of the play screen.
- [x] I'm not really sure if this one will be easy to fix or not, but if you swipe your mouse cursor over a box quickly enough, the move buttons will remain visible even though your cursor is no longer on top of the box.
- [x] The view shouldn't scroll unless the level is too large to fit on screen. Remember, if the level does fit on screen (and therefore scrolling is disabled), it should be centered.
- [x] The `Restart` button doesn't seem to do anything, except reset the vertical scroll bar to the top of the screen.
- [x] Add back the bottom right bar that displays the `Moves` and `Distance`.
- [x] Add back the level number/name indicator in the bottom left corner of the screen.
- [x] One thing I think you should consider is removing the `Level Select` button from the top left bar, and changing the `Exit` button to have that functionality (more specifically, it would return you to either the level select or the editor, depending on where you loaded the level from). It seems overcomplicated to have an additional button for returning to the main menu, when you could just exit to the level select and then click `Back`.

**Comment by grady404** [comment]
Do you think we should change `creator-score` to `creator-scores`? Which one makes more sense?

**Comment by cooperuser** [comment]
I like `creator-score` better. Also, did you like the test level? ignoring the stuff on the right?

**Comment by grady404** [comment]
It seemed a bit strange, and more about shoving annoying blocks around than actually solving puzzle elements. Also, I think we should only use colored blocks if they start in different areas of the board (so that it's kind of like one block has to "rescue" another), because if we include colored blocks just for the sake of including colored blocks our levels will suffer from "oh wait I got a block on the pad, but it's the wrong color block, and now I have to redo the entire thing" syndrome.

**Comment by cooperuser** [comment]
Yeah I understand that, but this was just for testing the colored blocks.

**Comment by grady404** [comment]
Yeah, I realize that

**Comment by cooperuser** [comment]
Btw I am currently working on these minor changes, anything else that needs to be changed?

**Comment by grady404** [comment]
Created a working level converter! So as soon as you fully implement the overhaul (see #73) I can copy all the levels over.

![screen shot 2016-10-13 at 6 47 12 pm](https://cloud.githubusercontent.com/assets/10258414/19373008/864606fc-9175-11e6-9bf6-61e877289dee.png)

**Comment by grady404** [comment]
Oh yes, it seems you didn't see my newest issue, it's #73

**Comment by cooperuser** [comment]
Oh and by the way, the reason a bunch of the issues that weren't supposed to be closed were was because I was in a hurry to push the commit.

**Comment by cooperuser** [comment]
And this issue is #73...

**Comment by grady404** [comment]
oh wait I'm an idiot, this _is_ #73

**Comment by grady404** [comment]
Yeah, I covered all the important fixes/changes

**Comment by cooperuser** [comment]
Oh can you make all of the bullet points at the top be check boxes? that way I can check them off.

**Comment by grady404** [comment]
Sure

**Comment by grady404** [comment]
You know _you_ can edit _my_ posts right?

**Comment by cooperuser** [comment]
Yeah i'm just not sure how that would work so I decided to ask you

**Comment by grady404** [comment]
Wrong update number, should have been `0.3.2` but just make the next one `0.3.3`

**Comment by cooperuser** [comment]
`0.3.2`? how come?

**Comment by cooperuser** [comment]
....

**Comment by cooperuser** [comment]
What did you even change there?

**Comment by grady404** [comment]
Something was wrong with the formatting of Level 1. Just read the update description

**Comment by cooperuser** [comment]
..... I dont think that needs a version bump...

**Comment by grady404** [comment]
Yes it does, because the game's files were edited. I'm about to leave, but one more thing before I do – about the scrolling, users shouldn't be able to scroll _past_ the boundaries of the level like they currently can.

**Comment by grady404** [comment]
For example, if they're trying to scroll to the top left corner, they shouldn't be able to go past the point where the top-left-most point on the level board is in the top left corner of the screen.

**Comment by cooperuser** [comment]
Ever? what if the level extends that way?

**Comment by grady404** [comment]
Well what I'm saying is, if the user tries to scroll to the top left corner for instance the game should only let them scroll this far (pretend that the level is large enough to be scrollable, even though this one wouldn't be):

![screen shot 2016-10-13 at 10 46 53 pm](https://cloud.githubusercontent.com/assets/10258414/19376933/055c252c-9197-11e6-9bc8-d2bbf9dc3c94.png)

They shouldn't be able to go this far:

![screen shot 2016-10-13 at 10 47 05 pm](https://cloud.githubusercontent.com/assets/10258414/19376939/10518c9c-9197-11e6-92db-f7cb008c0cb0.png)

**Comment by cooperuser** [comment]
Oh, I see, I thought you meant scroll the other way and lock the entire screen at the same time, I see, I will fix that

**Comment by grady404** [comment]
Oh and another thing I noticed, when you scroll the game items appear _above_ the user interface, like this:

![screen shot 2016-10-13 at 10 54 50 pm](https://cloud.githubusercontent.com/assets/10258414/19377077/112975fc-9198-11e6-815a-e9b9b35c115e.png)

**Comment by cooperuser** [comment]
Ah, thanks for pointing that out

**Comment by cooperuser** [comment]
![screen shot 2016-10-13 at 11 35 43 pm](https://cloud.githubusercontent.com/assets/21961037/19377798/cfceae00-919d-11e6-9ab3-915960ceba3a.png)
As I was testing some things out, I accidentally did this... It looks really cool but I'm not sure if it is beneficial.

**Comment by grady404** [comment]
You know what? The outline might be useful, but not for the buttons... I was thinking about making it so that a block temporarily faded to transparent when you selected it, so that you could clearly see the color of the plate beneath it. That will be something we can worry about later though

**Comment by grady404** [comment]
Once you get around to fully implementing the overhaul into the main game, this might come in handy: [`Level Converter.zip`](https://github.com/cooper-anderson/Blockade/files/528954/Level.Converter.zip)

Pretty straightforward, just drop all the level files you want to convert into the `old-levels` folder, then start the program in Python 2.7 and type the name of each file. The new versions will appear in the `new-levels` folder under the same name.

**Comment by grady404** [comment]
Think you'll be able to fix this last issue here?

**Comment by cooperuser** [comment]
Not entirely sure... I have tried but nothing has worked yet. I will continue to look into it.
