### ISSUE TITLE
Show Level number and name in play mode

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#77]
Make it show the level number and name in play mode. Only show the number if applicable (only when playing default levels).

**Comment by grady404** [comment]
I assume "only show the name if applicable" also applies?

**Comment by cooperuser** [comment]
Yes

**Comment by grady404** [comment]
Ok cool, no more `Debug`

**Comment by cooperuser** [comment]
Well, the level `0` `debug` is the name of the level the user gets sent to if something goes wrong

**Comment by grady404** [comment]
Well, the level is called `Debug`, but what I meant is it doesn't say `Debug` anymore if the level doesn't have a name

**Comment by cooperuser** [comment]
Correct

**Comment by grady404** [comment]
wait a minute, _what_? Why is there a "number" attribute? I assume that's temporary

**Comment by grady404** [comment]
Also, if the bottom left thing doesn't display a number the alignment looks off, so I would try to fix that

![screen shot 2016-10-13 at 11 46 10 pm](https://cloud.githubusercontent.com/assets/10258414/19378035/4a3a2038-919f-11e6-9878-1f068cab6f00.png)

**Comment by cooperuser** [comment]
The `number` attribute is for the default levels.... or should `default-level` be a flag where it checks the file name?

**Comment by grady404** [comment]
But the default levels are saved according to their number (e.g. `level15.json`)

**Comment by cooperuser** [comment]
But what if a user names a level `level24.json` or something

**Comment by grady404** [comment]
Then it will display the number `24`...

**Comment by cooperuser** [comment]
I think there should be a `default-level` flag, then it would integrate with the progress system more

**Comment by grady404** [comment]
Well, with the current way we are storing the levels the level number is in the file name. But I actually think we should change that so that the file name is the same as the name of the level (for example, `Four Corners.json`) and create a file called `order.json` or `sequence.json` or something like that that looks like what I typed out below (it is ordered by page). If you're not sure why I made it like this, see the bottom part of issue #58.

``` JSON
{
    "levels": [
        [
            "First Steps",
            "Not So Easy",
            "Doubling Up",
            "Saucer",
            "Globular",
            "Symbiosis",
            "The Climb",
            "Which One?",
            "Correspondence",
            "Underground Heist",
            "Spire",
            "Surprisingly Simple",
            "Mushroom",
            "Easy Way Out",
            "Two-Block Shuffle",
            "Crown"
        ],
        [
            "Triumvirate",
            "Satellite",
            "Four Corners",
            "Jailbreak"
        ],
        [
            "Hyrule Field I",
            "Hyrule Field II",
            "Hyrule Field III",
            "Snowpeak Ruins"
        ]
    ]
}
```

Eventually, we will change this so that the file names are UUIDs (see #58), and the level name will once again be an attribute in the `info` section of the JSON.
