### ISSUE TITLE
Integrate working versioning system

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#8]
The game has been at stage 'alpha v0.0.1' since its inception... this needs to change.

**Comment by grady404** [comment]
Just change the label to "under development" or something for now, don't have a version number until you actually release the game to the public (even if it's not the "official" release).

**Comment by cooperuser** [comment]
So this entire time, I have been thinking of ways of going about the version labeling system. I think that every time we commit a change, we add 1 to the third digit in the version e.g. `v0.0.1`, `v0.0.2`...,

**Comment by cooperuser** [comment]
And I would consider the jump to GitHub, a +1 to the second digit, so right now we would be at `v0.1.21`

**Comment by grady404** [comment]
I wouldn't use that yet, since we're still in the development phase. I think the way this will work eventually is, we'll make this GitHub thing private (because we're going to sell the game, right?) and just use it privately for the development process. That way, we don't have to bump up the version for _every little change_ we add, we only release an update when we've made a lot of small changes. The rightmost digit is bugfixes/minor improvements, the middle digit is new content, and the leftmost digit is complete overhauls to the entire game.

**Comment by cooperuser** [comment]
that makes sense, but isn't what we are currently doing small bugfixes and minor improvements?

**Comment by grady404** [comment]
Yeah, but we don't need to increment the rightmost number for every single bugfix/improvement, we should only do that when there are a lot of minor improvements.

**Comment by grady404** [comment]
When we release the game into alpha, it will be paid so we won't keep it public on GitHub anymore, we'll just use this space for private development, and every time we accumulate enough changes we'll push an update.

**Comment by grady404** [comment]
See my stuff in general discussion/level name and number thread. This thing really needs better notifications

**Comment by cooperuser** [comment]
hahahahaha http://gitify.io/

**Comment by cooperuser** [comment]
i was just looking into that

**Comment by grady404** [comment]
ah thanks so much for that LMFAO

**Comment by cooperuser** [comment]
but I feel that with this versioning system, previous versions of the game will be easier to document, and keep track of version changes

**Comment by grady404** [comment]
Doesn't GitHub take care of that anyway?

**Comment by cooperuser** [comment]
and whats the harm to incrementing the last digit, it isn't in base 10, the number can be like `v0.1.123`

**Comment by grady404** [comment]
I know... but then it'll be weird, because the public will see the updates as 0.1.0, 0.1.15, 0.1.33, 0.1.56, etc. so what about this? We add a fourth digit, but we don't actually display it in the game anywhere, we only use it to keep track of it ourselves

**Comment by cooperuser** [comment]
thats how most games are though

**Comment by cooperuser** [comment]
for example, webstorm is currently on `2016.2.3`, but only ever shows `2016.2` to the user

**Comment by grady404** [comment]
Not really... I think the fourth digit would be a pretty foolproof system

**Comment by grady404** [comment]
Yeah that's what I was saying... it doesn't show the fourth digit to the user

**Comment by cooperuser** [comment]
but the third digit, is our fourth digit, and many games skip around. Pretty much every MMO has the last digit as a long number that jumps upwards

**Comment by grady404** [comment]
So? We don't have to be like "pretty much every MMO"... I think a fourth digit would be a better way to do it, but it's up to you

**Comment by grady404** [comment]
And did you fix my "minor thing" or not?

**Comment by cooperuser** [comment]
oh i havent checked yet

**Comment by grady404** [comment]
Ok cool, one last minor thing you should fix, for now make the version "indev 0.0.0", and make it so that "indev" versions correspond to purple (the way alpha is red and beta is yellow), and every time you make a change bump up the last digit by 1

**Comment by grady404** [comment]
Or if you can't do purple, just pick some other color that makes sense

**Comment by cooperuser** [comment]
okay that works

**Comment by cooperuser** [comment]
oh and i think i got notifications working
