### ISSUE TITLE
Double Selector Bug on showMoveButtons Flag

### ISSUE THREAD

**Issue by cooperuser** [cooper-anderson/Blockade#82]
When you have both the `showMoveButtonsUntilHover` and the `showMoveButtonsUntilClick` flag, it creates two selectors. Fix this.

**Comment by grady404** [comment]
Minor technicality, `showMoveButtonsUntilClick` should override `showMoveButtonsUntilHover`, not the other way around.

**Comment by cooperuser** [comment]
It doesn't, which ever comes first does.

**Comment by cooperuser** [comment]
But I could change that

**Comment by grady404** [comment]
Ah, okay, that makes a bit more sense but I still think `UntilClick` should override in all cases

**Comment by cooperuser** [comment]
I am changing it now

**Comment by cooperuser** [comment]
Fixed
